### ISSUE TITLE
Consolidate Status and Status Reason (Separately)

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#2163] opened 2024-12-05 19:57 UTC
## User Story - Business Need
We want to consolidate notification failure `status` and `status_reasons` to simplify things for us and our clients. The two are being separately consolidated. For our clients, they should only see two failure `status` options (`temporary-failure` and `permanent-failure`). 

`status_reason` is to be consolidated as well, only allowing for the values specified in the [ADR](https://github.com/department-of-veterans-affairs/vanotify-team/blob/main/ADR%20Log/0026-status-reasons-failure-mapping.md).

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** Service using VA Notify
**I want** consistency and to know if I should retry or not
**So that** I can handle notifications appropriately

### Additional Info and Resources

[ADR](https://github.com/department-of-veterans-affairs/vanotify-team/blob/main/ADR%20Log/0026-status-reasons-failure-mapping.md) covering the change

Considering how few services use callbacks, the impact is likely to be zero.

## Acceptance Criteria

- [x] ADR status and status_reasons are included and are the only status_reasons used when updating notifications
- [ ] This work is added to the sprint review slide deck (key win bullet point and demo slide)

## QA Considerations

This is a fairly large overhaul of the possible responses, so it will require testing all of the outcomes.
Add status_reasons into automation (may be on a second ticket)

## Out of Scope
Adding the new logging messages for these status_reasons. Eventually we want to pass around objects that have: `status`, `status_reason`, and `log_message`, but creating that object and implementing it are out of scope.

**Comment by EvanParish** [comment] 2024-12-13 22:41
Chris and I have been working at finding and updating all of the outdated statuses and reasons. We are mostly there. The tests still need some work however. We'll get to that on Monday and hopefully begin testing in Dev soon after.

**Comment by EvanParish** [comment] 2024-12-16 23:10
There have been more changes than anticipated. This PR is going to be a pretty big one unfortunately. (27 files changed so far) A lot of the changes are simply removing technical-failure or changing it to permanent-failure, so hopefully it's not too bad to review.

**Comment by cris-oddball** [comment] 2024-12-19 21:16
PR approved and merged; deployed to Perf for testing.

**QA FAILED**

The ADR states:
- `Undeliverable - Phone number is invalid` presumably when we get a Twilio 2164 for 'not valid mobile' and 21635 for 'landline'. The code is instead returning `Undeliverable - Individual unreachable` and should be updated.
- `Undeliverable - Phone number is invalid` presumably when we get a Pinpoint response of 'record_status': 'INVALID'. The code is instead returning `Undeliverable - Individual unreachable` and should be updated.
- `Undeliverable - Individual unreachable` for hard bounce when SES returns `"eventType":"Bounce","bounce", "bounceType":"Permanent"` or celery reports `permanent-failure - Failed to deliver email due to hard bounce - in process_ses_results for notification c2fcdc32-70b3-4c94-9aaa-0b8ed5dd73b2`  The code is instead returning `Undeliverable - Unable to deliver` and should be updated.

More testing results to follow.

**Comment by cris-oddball** [comment] 2024-12-19 21:33
**TESTING NOTES** 

- All available Twilio statuses were validated against the ADR and this document on [delivery status testing](https://github.com/department-of-veterans-affairs/vanotify-team/blob/main/Engineering/Quality%20Assurance/lambda_test_events/testing_delivery_lambda.md). That test document needs to be updated, but with the exception of the 3 bullet points above, all testing resulted in the new expected statues
- AWS Pinpoint has changed their destination simulated numbers such they are no longer available. This was verified by @ChrisJohnson-CDJ and @EvanParish. As such we will need to rely on unit tests for the bulk of testing Pinpoint statuses. 
  - We did test sending to an invalid, and the response is incorrect as noted in the bullet points above. 
  - We did validate that when a VAProfile does not have contact info, that the response is `"status": "permanent-failure", status_reason": "Undeliverable - No VA Profile contact information"`
- The regression validated that preferences-declined is now `permanent-failure` and `Undeliverable - Preferences declined in VA Profile`
- @kalbfled was unable to find a deceased users in the [test users document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv) that actually triggered the `permanent-failure` status; all notifications sent to all users in this list came back delivered. I recall this issue the last time I tried to test deceased, so we are unable to validate this.
- AWS SES - as noted in the bullet point above, there is one status_reason that needs to be updated. AWS SES simulated email addresses now only work if the account is in the sandbox, otherwise it indicates that all emails were delivered, so we are also unable to fully validate SES.

**Comment by cris-oddball** [comment] 2024-12-19 22:28
2nd PR approved and merged, deploying to Prod.

**Comment by cris-oddball** [comment] 2024-12-19 22:36
QA

Hotfix tests

- [ ] Postman - An sms sent via Pinpoint to a number that does not exist (+12025551212), expect "status": "permanent-failure" and "status_reason": "Undeliverable - Phone number is invalid"
- [ ] Postman - An email sent via SES to an address that does not exist (sparticus@docme360.com), expect "status": "permanent-failure" and "status_reason": "Undeliverable - Individual unreachable"
- [ ] Twilio delivery status lambda - send test payload for error 21614, expect a log that includes "status": "permanent-failure" and "status_reason": "Undeliverable - Phone number is invalid"
- [ ] Twilio delivery status lambda - send test payload for error 21635, expect a log that includes "status": "permanent-failure" and "status_reason": "Undeliverable - Phone number is invalid"

**Comment by cris-oddball** [comment] 2024-12-19 22:47
ON TO PROD!

**Closed** 2024-12-19 23:21 UTC
Labels: Notify, QA, Dev Reviewed, PM Reviewed, QA Reviewed
