### ISSUE TITLE
IIR - Integrate permission check into contact info lookup

### ISSUE THREAD

**Issue by stevelong00** [department-of-veterans-affairs/notification-api#1953] opened 2024-08-22 15:42 UTC
## User Story - Business Need

[Companion Ticket](https://app.zenhub.com/workspaces/va-iir-6508c0bd79e64e0fb5855caf/issues/gh/department-of-veterans-affairs/va-iir/895) from VA-IIR Team

Currently we have two celery tasks, one for looking up contact info and one for looking up communication permissions. We want to move the permissions check into the contact info lookup so that both can use a single call to Profile API.

### User Story(ies)

As a software developer working on the `notifications-api` repository
I want to integrate permission check into contact info lookup
So that I can both can use a single call to Profile API

### Additional Info and Resources

- [Parent spike with details in the comments](https://app.zenhub.com/workspaces/va-iir-6508c0bd79e64e0fb5855caf/issues/gh/department-of-veterans-affairs/va-iir/790)

- [Profile API Notes](https://docs.google.com/document/d/1rH2Q9ijrI41EOGGZfjaWP3To5AvbttmqMGSdz6JbW94/edit#heading=h.pe5qko4ekebd)

Currently we have two celery tasks, [contact_information_tasks.py](https://github.com/department-of-veterans-affairs/notification-api/blob/081de20b3c5cd02764afe1b59a2d844c53a3defa/app/celery/contact_information_tasks.py) and [lookup_recipient_communication_permissions_task.py](https://github.com/department-of-veterans-affairs/notification-api/blob/081de20b3c5cd02764afe1b59a2d844c53a3defa/app/celery/lookup_recipient_communication_permissions_task.py).

We want to combine these into a single task, which makes a single call to Profile API.  The simplest way to do this is to integrate the permission check into the contact info lookup, so that contact info is returned only when it both exists and has permissions enabled.

## Acceptance Criteria

- [ ] In the [VAProfileClient](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/va/va_profile/va_profile_client.py) class, create a new method `get_contact_info_with_permission`.  This makes a single call to the Profile API v3 to fetch email, phone, and permissions.  If permissions are not granted for the requested email or phone number, a new exception should be raised indicating that permissions were denied.
 
- [ ] In the [lookup_contact_info](https://github.com/department-of-veterans-affairs/notification-api/blob/081de20b3c5cd02764afe1b59a2d844c53a3defa/app/celery/contact_information_tasks.py) celery task 
    - [ ] When the `COMBINE_CONTACT_INFO_AND_PERMISSIONS_LOOKUP` flag is enabled, replace calls to `get_email` or `get_telephone` with calls to `get_contact_info_with_permission`
    - [ ] add a check for the new permissions denied exception and handle it appropriately.

- [ ] In [process_notifications.py](https://github.com/department-of-veterans-affairs/notification-api/blob/081de20b3c5cd02764afe1b59a2d844c53a3defa/app/notifications/process_notifications.py), when the `COMBINE_CONTACT_INFO_AND_PERMISSIONS_LOOKUP` flag is enabled, bypass both places where the `lookup_recipient_communication_permissions` task is inserted

## QA Considerations

All business logic should be the same as before.  The only difference with these changes should be that the permission check now happens within the same task as the phone or email lookup.

**Comment by cris-oddball** [comment] 2024-09-18 21:02
PR is approved and merged. There is follow-up work. The Prod feature flag in this PR is set to False, meaning it is off and using the default code in Prod. Will hold this ticket open for QA testing.

**Comment by cris-oddball** [comment] 2024-09-20 21:10
PR approved and merged after the revert earlier this week. Currently deployed to Perf. Will begin manual testing for edge cases next week.

**Comment by cris-oddball** [comment] 2024-09-23 17:31
Edge cases so far:
- callbacks are working with the feature flag enabled
- a vet with no contact info is still working as expected

Test case failures:
- with feature flag off in staging (had to cut a branch for that), notifications that exercised the default send scenarios were stuck in created. Kyle and Evan working on a fix.
- discrepancies when sending to a deceased veteran (test user 1411910), in perf with FF on the response is delivered, in staging with FF off, the response is  a permanent failure "Failed to deliver email due to hard bounce","
- still looking into edge cases

**Comment by cris-oddball** [comment] 2024-09-23 20:36
I went back to the original tickets for the explicit send feature and don't really see any other edge cases. 

Kyle and Evan have been working on a fix for the 'stuck in created' issue, expect to see a PR 'soon'. They are also looking at that deceased veteran hard bounce vs delivered issue.

**Comment by cris-oddball** [comment] 2024-09-23 21:47
A fix is up. That fix has been deployed to Perf and Staging
PERF: Feature flag is enabled | True
STAGING: Feature flag is disabled | False

Now have a known good deceased PID for perf/staging, will test with that one.

will retest things Tuesday morning.

**Comment by cris-oddball** [comment] 2024-09-24 12:23
**QA TESTING IN PROGRESS**

**PERF - ENABLED** 
Has feature flag set to True (enabled, will use V3)
Callback: /internal/qa-staging-automation-callback

- [ ] Regression passes (exercises recipient identifier lookups and the 6 default send scenarios)
- [ ] status `delivered` has no status_reason
- [ ] status `preferences-declined` where recipient has opted-out of a notification has status_reason 'Contact preferences set to false'
- [ ] status `preferences-declined` where recipient has not set a preference for notifications has status_reason 'No recipient opt-in found for explicit preference'
- [ ] status 'permanent-failure' where recipient is deceased (MPI lookup) has status_reason 'Beneficiary has deceased status in MPI'
- [ ] status 'permanent-failure' where VAPROFILEID has no contact info has status_reason 'No contact info found from VA Profile'
- [ ] Callbacks work as expected


**STAGING - DISABLED**
Has feature flag set to False (disabled, does not use V3)
Callback: /internal/qa-staging-automation-callback

- [ ] Regression passes (exercises recipient identifier lookups and the 6 default send scenarios)
- [ ] status `delivered` has no status_reason
- [ ] status `preferences-declined` where recipient has opted-out of a notification has status_reason 'Contact preferences set to false'
- [ ] status `preferences-declined` where recipient has not set a preference for notifications has status_reason 'No recipient opt-in found for explicit preference'
- [ ] status 'permanent-failure' where recipient is deceased (MPI lookup) has status_reason 'Beneficiary has deceased status in MPI'
- [ ] status 'permanent-failure' where VAPROFILEID has no contact info has status_reason 'No contact info found from VA Profile'
- [ ] Callbacks work as expected

**Comment by AdamKing0126** [comment] 2024-09-24 13:59
Oh! The checkboxes are filled in now!  Maybe I spoke too soon?

**Comment by cris-oddball** [comment] 2024-09-24 15:34
@AdamKing0126 you can refer to the [PR hotfix ](https://github.com/department-of-veterans-affairs/notification-api/pull/2007)that Evan and Kyle worked on and discuss with Evan if you have any questions.

**Comment by k-macmillan** [comment] 2024-09-24 16:59
PR has been merged.

**Comment by cris-oddball** [comment] 2024-09-24 17:06
This is going straight up to Prod. Closing ticket.

**Closed by cris-oddball** 2024-09-24 17:06 UTC
Labels: Notify
