### ISSUE TITLE
Pull from Github Packages instead of ECR

### ISSUE THREAD

**Issue by punitladtw** [department-of-veterans-affairs/notification-api#59] opened 2020-05-18 14:57 UTC
- [ ] Update task definition to pull from Github Packages
- we may need to setup the proper routing so fargate can reach out to github packages 
- we will also need to setup github credentials so fargate can access the github packages docker repository

**Comment by ffafara-tw** [comment] 2020-06-04 19:34
Duplicate of #39

**Closed** 2020-06-04 19:37 UTC
