### ISSUE TITLE
[BUG] Spacing issues with paragraphs nested in lists

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#391] opened 2021-03-01 19:16 UTC
# Describe the Bug
When attempting to create a COVID KMI email with formatting that required paragraphs nested in lists there is an extra break line tag (br) added.

# To Reproduce

1. List item 1\n\n
\tShould be paragraph in the list item without extra br above

# Expected Behavior
There should not be <br> between paragraphs of a list item in the generated html email.

# Actual Behavior 
An extra line appears if a list item contains one or more paragraphs.

# Relevant Story
If applicable, link the related story here.

# Screenshots

# Desktop
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

# Smartphone
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

# Additional Context
This bug affects html emails.  Fixing this bug should not change any existing behavior.

**Comment by saman-moshafi-va** [comment] 2021-04-21 20:50
This content 
`\n\n1. List item 1\n Should be paragraph in the list item without extra br above`
seems to work while this content causes the problem
`\n\n1. List item 1\n\n\tShould be paragraph in the list item without extra br above`

**Comment by ffafara-tw** [comment] 2021-04-28 15:30
Three possible approaches:
1. CSS route:
 - Use global CSS (style header in jinja template) with selectors for paragraphs instead of inline styles for paragraphs.
- Potential problems - global styles might now work across all email clients; inline styles are usually recommended for emails

2. Provide information to renderer wether paragraph is inside list item block
- render can use that information to render differently (or call different different method altogether)
- requires changes to Markdown (and potentially to Lexer)
- Potential problems - can we supply our own Markdown?

3. Do not modify list rules. Modify lexer so that it never creates newline token.

**Comment by saman-moshafi-va** [comment] 2021-05-04 20:49
The solution is mix of options 2 and 3. Created an md file stating how mistune works, how notification-utils uses it and how we fixed it.

**Comment by saman-moshafi-va** [comment] 2021-05-14 18:29
### Before
<img width="736" alt="Screenshot 2021-02-18 at 16 38 26" src="https://user-images.githubusercontent.com/56931061/118313043-3fadb000-b4c0-11eb-8054-092b71acc696.png">

### After

![image](https://user-images.githubusercontent.com/56931061/118313401-af239f80-b4c0-11eb-8dc4-01ee79d96347.png)

**Comment by saman-moshafi-va** [comment] 2021-05-14 18:31
As per last comment The issue is fixed. To ensure the fix does not cause any issues We sent a few emails from the same templates and compared them with the emails that were sent before.  The issue is fixed and no issue is introduced.

**Comment by TWs-DevenS** [comment] 2021-05-14 20:49
This fix has been verified
Before snd After screen shots have ben attached. 
Check was performed on other emails impacted by the code fix, with no issues
Closing ticket

**Closed** 2021-05-14 20:49 UTC
Labels: Bug
