### ISSUE TITLE
BUG: Userflows fails

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#928] opened 2022-10-31 14:23 UTC
## Describe the bug
`test_send_text_with_profile_id` fails with an undelivered message. It loops over it for 30 seconds using sleep (questionable choice), waiting for the correct status change. The status never changed. Looked up the notification half an hour later and it wsa still "sending". 

For some reason this does not fail if we deploy the userflows lambda.

**Comment by mjones-oddball** [comment] 2022-11-02 13:43
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/928?planning-poker) with Zenhub @cris-oddball @EvanParish @ianperera @jakehova @k-macmillan @kalbfled @trevor2718

**Comment by trevor2718** [comment] 2022-11-03 15:44
@cris-oddball @ldraney I cannot replicate the issue on my end, I am having `ERROR lambda_functions/user_flows/test_retrieve_everything.py - botocore.exceptions.NoRegionError:`  error, might need to connect to AWS to produce the error.

**Comment by cris-oddball** [comment] 2022-11-03 20:01
^ note about the above error, the user flows tests cannot be run locally, which is why the observed errors were returned. 

Looping for 30 sec may also be a red herring.

**Comment by cris-oddball** [comment] 2022-11-03 20:08
Tests all pass (no logging on tests, so not possible to see what was sent or how many times the tests went through the `wait_for_status()` loop ) when running the `Deploy to Dev ` GitHub action with `Include Lambda in deployment? ` checked.

When running Deploy to Dev ` GitHub action with `Include Lambda in deployment? ` **not** checked, the tests will fail.

When using the Lambda test event in the AWS User Flows lambda console with the payload `{"environment": "dev"}` the tests will fail.


An example failed test response (partial) from User Flows:
```
for _ in range(30):
service_jwt = encode_jwt(service_id, service_test_api_key)
notification_status_response = get_notification_status(notification_id, notification_url, service_jwt)
assert notification_status_response.status_code == 200
if notification_status_response.json()['status'] == desired_status:
return notification_status_response.json()
time.sleep(1)
>       pytest.fail(f"Response did not reach desired status '{desired_status}': {notification_status_response.json()}")
E       Failed: Response did not reach desired status 'delivered': {'billing_code': None, 'body': 'This is a test SMS message', 'completed_at': None, 'created_at': '2022-11-03T17:52:06.798719Z', 'created_by_name': None, 'email_address': None, 'id': 'a2b1f2f3-560d-464a-951b-fdfb638eabe6', 'line_1': None, 'line_2': None, 'line_3': None, 'line_4': None, 'line_5': None, 'line_6': None, 'phone_number': '+14435679091', 'postage': None, 'postcode': None, 'provider_reference': 'cae0c17e-afe4-4016-848e-4d938926032b', 'recipient_identifiers': [{'id_type': 'VAPROFILEID', 'id_value': '203'}], 'reference': None, 'scheduled_for': None, 'sent_at': '2022-11-03T17:52:07.756810Z', 'sent_by': 'twilio', 'status': 'sending', 'status_reason': None, 'subject': None, 'template': {'id': '2c3c49b5-d676-4d08-a286-322c600de452', 'uri': 'https://dev.api.notifications.va.gov/v2/template/2c3c49b5-d676-4d08-a286-322c600de452/version/1', 'version': 1}, 'type': 'sms'}
test_retrieve_everything.py:254: Failed
```

Taking the ID from this example and searching the celery logs for that time frame (ecs/notification-celery/5f66a56f48124f0fb20ab64ffa78a0a6), the following logs were observed, noting that this is expected because Twilio cannot respond the endpoint because they are not on the VA Network.

```
2022-11-03T17:51:22 delivery delivery INFO no-request-id "Start sending SMS for notification id: 2ba9431b-6699-4e07-af6e-8f8b46f566ae" [in /app/app/celery/provider_tasks.py:25]
[2022-11-03 17:51:22,139: INFO/ForkPoolWorker-4] Start sending SMS for notification id: 2ba9431b-6699-4e07-af6e-8f8b46f566ae
2022-11-03T17:51:22 delivery delivery ERROR no-request-id "API POST request on https://dev.api.notifications.va.gov/notifications/sms/twilio/2ba9431b-6699-4e07-af6e-8f8b46f566ae failed with None" [in /app/app/celery/research_mode_tasks.py:96]
[2022-11-03 17:51:22,215: ERROR/ForkPoolWorker-4] API POST request on https://dev.api.notifications.va.gov/notifications/sms/twilio/2ba9431b-6699-4e07-af6e-8f8b46f566ae failed with None
2022-11-03T17:51:22 delivery delivery INFO no-request-id "Mocked provider callback request finished" [in /app/app/celery/research_mode_tasks.py:105]
[2022-11-03 17:51:22,215: INFO/ForkPoolWorker-4] Mocked provider callback request finished
2022-11-03T17:51:22 delivery delivery ERROR no-request-id "SMS notification delivery for id: 2ba9431b-6699-4e07-af6e-8f8b46f566ae failed" [in /app/app/celery/provider_tasks.py:52]
Traceback (most recent call last):
File "/app/app/celery/research_mode_tasks.py", line 93, in make_request
response.raise_for_status()
File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: NOT FOUND for url: https://dev.api.notifications.va.gov/notifications/sms/twilio/2ba9431b-6699-4e07-af6e-8f8b46f566ae
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/app/app/celery/provider_tasks.py", line 29, in deliver_sms
send_to_providers.send_sms_to_provider(notification, sms_sender_id)
File "/app/app/delivery/send_to_providers.py", line 78, in send_sms_to_provider
send_sms_response(provider.get_name(), str(notification.id), notification.to, notification.reference)
File "/app/app/celery/research_mode_tasks.py", line 66, in send_sms_response
make_request(SMS_TYPE, provider, body, headers, path)
File "/app/app/celery/research_mode_tasks.py", line 103, in make_request
raise api_error
requests.exceptions.HTTPError: 404 Client Error: NOT FOUND for url: https://dev.api.notifications.va.gov/notifications/sms/twilio/2ba9431b-6699-4e07-af6e-8f8b46f566ae
[2022-11-03 17:51:22,215: ERROR/ForkPoolWorker-4] SMS notification delivery for id: 2ba9431b-6699-4e07-af6e-8f8b46f566ae failed
Traceback (most recent call last):
File "/app/app/celery/research_mode_tasks.py", line 93, in make_request
response.raise_for_status()
File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: NOT FOUND for url: https://dev.api.notifications.va.gov/notifications/sms/twilio/2ba9431b-6699-4e07-af6e-8f8b46f566ae
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/app/app/celery/provider_tasks.py", line 29, in deliver_sms
send_to_providers.send_sms_to_provider(notification, sms_sender_id)
File "/app/app/delivery/send_to_providers.py", line 78, in send_sms_to_provider
send_sms_response(provider.get_name(), str(notification.id), notification.to, notification.reference)
File "/app/app/celery/research_mode_tasks.py", line 66, in send_sms_response
make_request(SMS_TYPE, provider, body, headers, path)
File "/app/app/celery/research_mode_tasks.py", line 103, in make_request
raise api_error
requests.exceptions.HTTPError: 404 Client Error: NOT FOUND for url: https://dev.api.notifications.va.gov/notifications/sms/twilio/2ba9431b-6699-4e07-af6e-8f8b46f566ae
[2022-11-03 17:51:22,237: INFO/ForkPoolWorker-4] Task deliver_sms[9d8df5d7-c32e-455e-9a27-92f1aa88935c] retry: Retry in 0s
[2022-11-03 17:51:22,261: INFO/MainProcess] Received task: deliver_sms[9d8df5d7-c32e-455e-9a27-92f1aa88935c] 
2022-11-03T17:51:22 delivery delivery INFO no-request-id "Start sending SMS for notification id: 2ba9431b-6699-4e07-af6e-8f8b46f566ae" [in /app/app/celery/provider_tasks.py:25]
[2022-11-03 17:51:22,269: INFO/ForkPoolWorker-4] Start sending SMS for notification id: 2ba9431b-6699-4e07-af6e-8f8b46f566ae
[2022-11-03 17:51:22,278: INFO/ForkPoolWorker-4] Successfully sent sms for notification id: 2ba9431b-6699-4e07-af6e-8f8b46f566ae
2022-11-03T17:51:22 delivery delivery INFO no-request-id "deliver_sms took 0.0114" [in /app/app/celery/celery.py:20]
[2022-11-03 17:51:22,280: INFO/ForkPoolWorker-4] deliver_sms took 0.0114
[2022-11-03 17:51:22,281: INFO/ForkPoolWorker-4] Task deliver_sms[9d8df5d7-c32e-455e-9a27-92f1aa88935c] succeeded in 0.011439357011113316s: None
```

**Comment by cris-oddball** [comment] 2022-11-04 21:45
The plot thickens.

Running the code locally (copied code to a local repo, added env var for the secrets necessary to run the tests) against the hosted DEV APIs, the tests are flaky.  But the ones that fail through Github actions pass.  They also use pinpoint as the provider, not twilio.

Thus far we know... the tests in question fail with the "status" property in the response from GET` /notification`  never being set to "delivered"

- two tests for sending an SMS consistently fail when User Flows is run via the Deploy to Dev GitHub action without deploying the lambdas. The failing tests consistently show Twilio as the provider.
- all tests consistently pass when User Flows is run via the Deploy to Dev GitHub action **and** that action deploys the lambdas. We do not know the provider since the tests do not log anything nor do they print anything to stdout.
- all tests pass when User Flows is modified to run locally against the hosted DEV APIs. The provider used is Pinpoint.
- Twilio is not capable of sending us the delivered status because it has no access to the internal network (so how are we handling this case for the "status" response in the GET BY ID `/notification` route?)
- Kyle was able to reproduce in Postman with Twilio set as the provider 

At this moment, my thoughts are:

1. Determine why we never get back a "delivered" in the "status" response in the GET BY ID `/notification` given the service_id, the api key, the template ID, etc
2. Determine how we are supposed to report the  "status" response in the GET BY ID `/notification` when the provider is Twilio
3. Sunset User Flows in favor of a true e2e API regression as soon as possible
4. Do not use a lambda for the API regression.

**Comment by cris-oddball** [comment] 2022-11-07 15:58
The plot thickens again.  Whereas last Friday, running the tests locally against the DEV API, the provider was Pinpoint for Template ID `2c3c49b5-d676-4d08-a286-322c600de452`.

This morning (Monday), the same template ID but now the provider is Twilio. 
(debug stdout output)
```
Send SMS with profile ID; Template ID is 2c3c49b5-d676-4d08-a286-322c600de452
Provider for this call is twilio
Status at this time is sending
```

Since Twilio can never respond to us with a delivered status, these two tests (`test_send_text` and `test_send_text_with_profile_id`) should have the logic changed in the method `wait_for_status()` these tests us that repeatedly call the GET `/notifications/:id` route to see if the message has been delivered.

Something like (in pseudocode)
FOR loop
    send request
    if `sent_by` is `twilio` 
    then desired status should be `sending` (which means we initiated the call to twilio'

The remainder of the logic should then pass the assertions.

More critically, we need to understand why sometimes the call sends the request through pinpoint and sometimes it send it through twilio. This feels like a defect to since we should be in control of who the provider is, and not at the whimsy of the service.

**Comment by cris-oddball** [comment] 2022-11-07 17:29
Just capturing notes - question asked in va-notify-engineers:

OK, so for the template that User Flows sends, which is in service_id 93f39d73-c400-48c2-9b71-47e231a6855c and template_id 2c3c49b5-d676-4d08-a286-322c600de452  the provider_id on the template is null.
So, for User Flows, I am pretty sure the easiest fix is to just change the provider_id on that template to pinpoint. I do not see a way to do that through the UI, just the API? And before I do that....
Why is the service deciding to use pinpoint sometimes and twlio other times? Is that how the service is designed? Or is there actually some defect lurking here? Is anyone available to walk me through how our service chooses a provider?

**Comment by cris-oddball** [comment] 2022-11-09 19:35
@mjones-oddball What would you like me to do with this ticket? I don't see the point of changing the User Flows if I am replacing them with a better test harness for regression and once Dave completes his work, these tests should all pass (they appear to be passing today, actually).

**Comment by mjones-oddball** [comment] 2022-11-10 17:38
@cris-oddball am I understanding correctly that the root cause of the failure was the provider issue you unearthed? CC @k-macmillan

**Comment by cris-oddball** [comment] 2022-11-10 17:52
@mjones-oddball Correct. When a test fails, it also dumps output to stdout (console) and that output included the API key that was used to make the call (noting that when all the tests run, that API key is then subsequently deleted). So, the only time you'd see the API key was on a test failure, and the tests fail when the provider used is switched to Twilio.

**Comment by mjones-oddball** [comment] 2022-11-10 17:59
@k-macmillan You agree this can be closed? I think so.

**Comment by cris-oddball** [comment] 2022-11-10 18:51
@mjones-oddball @k-macmillan Oops, I left the wrong comment (thought this was another ticket - sigh). 
But yes, the root cause was the provider issue. No changes needed to User Flows if we are going to disallow that provider switching for sms.

**Comment by cris-oddball** [comment] 2022-11-14 15:31
Given that the cause of the failure was the provider bug, closing this (Will Not Fix) since the tests here, while not ideal, are working as intended.

**Closed by cris-oddball** 2022-11-14 15:31 UTC
Labels: bug, Notify
