### ISSUE TITLE
Remove Endpoints - letter-contact

### ISSUE THREAD

**Issue by EvanParish** [department-of-veterans-affairs/notification-api#1158] opened 2023-03-21 19:04 UTC
## User Story - Business Need

In the effort to clean up our code we need to investigate and remove unused endpoints. This ticket is to take a look at the endpoints under `/service/<uuid:service_id>/letter-contact` and remove the ones marked for removal. You can view the table of endpoints [here](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/VA%20Notify%20Endpoints.md).

### User Story(ies)
**As an** engineer
**I want** to clean up and reduce our codebase
**So that** it is easier to maintain and upgrade in the future.

### Additional Info and Resources
- [Endpoint Table](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/VA%20Notify%20Endpoints.md)
- [Endpoint Spreadsheet](https://docs.google.com/spreadsheets/d/18AfqlEOWlrnigauO57jA0VP3RMHTaP4luknqBxrcbuY/edit#gid=115873237)
- [How To Guide for similar code clean up for 1149](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Process/Coding/UnusedCodeRemoval.md)
## Engineering Checklist

- [x] Investigate the endpoints starting with `/service/<uuid:service_id>/letter-contact` to make sure they aren't being used
- [x] Remove tests associate with those endpoints
- [x] Remove the code associated with those endpoints (if possible). Make sure not to remove any code used by other parts of the application.

## Acceptance Criteria

- When the designated code and tests have been removed, the application retains full functionality. 

## QA Considerations
- [ ] The QA Regression Suite passes
- [x] The Cypress regression passes

## Potential Dependencies
- Make sure the removal of these endpoints doesn't affect the work Strike is doing.

**Comment by mjones-oddball** [comment] 2023-03-29 16:09
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1158?planning-poker) with Zenhub @cris-oddball @EvanParish @jakehova @justaskdavidb2 @k-macmillan @kalbfled @ldraney

**Comment by mjones-oddball** [comment] 2023-08-30 12:40
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1158?planning-poker) with Zenhub @nikolai-efimov

**Comment by nikolai-efimov** [comment] 2023-08-30 15:27
Estimating points for these tickets can be challenging due to the varying code volume and complexity of interconnections. An endpoint could range anywhere from 2 to 5 points for dev work.

**Comment by kalbfled** [comment] 2023-09-20 20:07
Nathan manually tested changes for this ticket.  (He says the Cypress regression is not appropriate for this.)  He tells me that the changes are good.

**Comment by cris-oddball** [comment] 2023-09-28 21:00
Code is merged to master and tagged as v1.6.12-1158-ep-removal. Sending to Perf.

**Comment by cris-oddball** [comment] 2023-09-28 21:19
Also sent up the Infra hotfix. Running regression.

**Comment by cris-oddball** [comment] 2023-09-28 21:24
190 passed, 3 xfailed in 157.02s (0:02:37)

**Closed by cris-oddball** 2023-09-28 21:24 UTC
Labels: Tech Debt, Notify, QA
