### ISSUE TITLE
Handle Twilio Error Code 30500 and Other Codes

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#2104] opened 2024-11-05 19:11 UTC
## User Story - Business Need
30500 is a [Twilio internal error](https://www.twilio.com/docs/api/errors/30500), and we should mark the notification as temporary-failure.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** VA Notify client
**I want** my notification updates to be as accurate as possible
**So that** I can make informed decisions

### Additional Info and Resources

The `_evaluate_status` method controls this behavior. This error code is not mapped, so it fell to a technical error. Add the mapping below to the twilio client `twilio_error_code_map`. There are too many Twilio statuses to effectively map, so we have to deal with them as we find them.

New constant for retryable:
```python
    RETRYABLE_STATUS_REASON = 'Retryable - Notification is unable to be processed at this time. Replay the request to VA Notify.'
```

```python
    '30500': TwilioStatus(30500, NOTIFICATION_TEMPORARY_FAILURE, RETRYABLE_STATUS_REASON),
```

`Unaccounted for Twilio Error Code`
Is handled differently from 
`Error code: <error code> existed but status for message: <message sid> was not failed nor undelivered`

## Acceptance Criteria

- [x] New constant added for retries in constants.py, listed in additional information
- [x] 30500 is added as a temporary-failure status with a message matching the additional information section
- [x] Add mappings for `30003`, `30004`, `30005`, `30006`, `30007`, `30024`
- [x] Add mapping for `21408`, `21610`, `21612`, `21614`, `21268`, `21635`, `60005`, 
- [x] This work is added to the sprint review slide deck (key win bullet point and demo slide)

## QA Considerations

- [ ]  Get an appropriately signed test body from the developer to be able to add this to the lambda testing. then test it.

**Comment by k-macmillan** [comment] 2024-11-26 22:19
Generate signature and message for every error code:
```python
for ts in TwilioSMSClient.twilio_error_code_map.values():
    print(
        generate_twilio_signature_and_body(
            token=FAKE_DELIVERY_STATUS_TOKEN,
            uri=FAKE_DELIVERY_STATUS_URI,
            error_code=str(ts.code),
            message_status='failed',
        )
    )
```

**Comment by cris-oddball** [comment] 2024-12-02 15:32
PR approved and merged, awaiting pipeline deploy. Regression is currently failing due to GLIBC issue re-surfacing, but this can still be deployed, tagged and validated.

**Comment by cris-oddball** [comment] 2024-12-02 22:09
Test bodies needed to be regenerated for the correct signature. Will resume testing tomorrow (Tuesday).

**Comment by cris-oddball** [comment] 2024-12-02 22:52
Resumed testing tonight, all test cases passed, sending to Prod. Updating Team Repo with instructions for validation.

**Closed** 2024-12-02 23:09 UTC
Labels: Notify, QA, Dev Reviewed, PM Reviewed, QA Reviewed, Feature
