### ISSUE TITLE
Deploy to staging environments

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#79] opened 2020-06-11 06:54 UTC
**Assumptions:** 
* Scripts will be the same for parameterizing the Terraform code
* Tagging piece will be done as part of this story
* Define the tagging strategy also be a part of this story _(team to visualize and confirm flow before this)_
* Using AWS TW account 

**Checklist:**
- [x] CI configuration additions to `staging-ci.yaml`
  - [x] Trigger ECS tasks for api, celery, celery-beat (`dev-deploy-api`, `dev-deploy-celery`, `dev-deploy-celery-beat`)
  - [x] Run migrations (`dev-run-migrations`)
  - [x] Add tagging (`create-tag`)
  - [x] Update staging env param store values as they are the same as dev at the moment -> the values that are the same (like twilio credentials) can remain the same. The other values are generated via terraform.
- [x] duplicate and amend api task definitions for staging (see `dev-api-task-definition.json`)
- [x] Evolve existing tagging strategy to account for different pipelines and their appropriate tagging formats 
  - [x] at end of development tag to indicate staging readiness with format `staging-vx.x.x` (incremented from latest tag)
     - [x] update existing incrementing to update based on latest tag with `staging-v` at the beginning
  - [x] at end of development, tag docker with `staging-vx.x.x` (new job)
  - [x] at end of staging, tag docker with `vx.x.x`(new job)
  -  [x] at end of staging, tag to indicate production readiness with format `vx.x.x`+1 (should match the `staging-vx.x.x` tag that triggered the staging pipeline)
- [x] light touch smoke test - hit status endpoint, verify version matches
    - status is ok and commit matches (hit _status endpoint)

**Resources:**
- [Tagging and CI visual flow](https://app.mural.co/t/thoughtworksveteransaffairs4407/m/thoughtworksveteransaffairs4407/1593186258007/a23b95bf270e242409c46afb78aee0b8212e5ae9)

**Comment by lingtran** [comment] 2020-06-30 20:56
Asks for dev sync for step ` run-migrations` ci job:
- does container name change according to environment?
- walk through the run migrations script in `Run migration task` step

**Comment by marisahoenig** [comment] 2020-07-14 15:57
Based on desk check, need to test that status code failure appears in pipeline. To test, we can hardcode an incorrect URL. Then, this can move on to review.

**Comment by marisahoenig** [comment] 2020-07-14 19:08
Confirmed that build fails when smoke test fails and the create tag step is not started  🎊 Moving to review/QA

**Comment by lingtran** [comment] 2020-07-15 21:23
Pair: @sarahproof / @lingtran 

We successfully tested staging, all except for actually sending an email due to bug that seems to be related to `email-from` value (a request requirement).

**Closed** 2020-07-17 20:25 UTC
Labels: Release
