### ISSUE TITLE
Ensure all notification status reasons are being captured

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#566] opened 2021-10-04 18:12 UTC
# Value Statement
**As** business line customer
**I want to** know all the possible statuses for my notifications
**So that**I understand what is happening with my notifications

# Acceptance Criteria
**GIVEN** a request to send a notification
**WHEN** we are unable to send the notification due to one of the reasons from the table below  
**THEN** notification is updated with status permanent failure and status reason uniquely identifying that reason

GIVEN notification request with VA Identifier
WHEN VANotify queries MPI
AND MPI returns Correlation Does Not Exist error
THEN notification status is set to permanent-failure
AND status_reason is set with a value that clearly indicates the root cause (Correlation Does Not Exist)

# Checklist

- [x]  Review MPI/VA Profile - Contact Information to ensure that failures are enumerated across all of the integrations and identify the corresponding notification status and status reason

- [x] VA Profile - Contact Preferences path to ensure that failures are enumerated across all of the integrations and identify the corresponding notification status and status reason

# Cross Functional Checklist

Mountebank
- [x] API - create mocks for any external services calls

# Assumptions
- The status and status reason is propagated to the database in the notifications table
- Status reason already exists, we need to make sure it is being set in all of the places it is being set 
- 

**MPI**
No such identifier *note: currently technical failure should be a permanent failure with a descriptor on why it is happening
Multiple VA Profile IDs *note: we stop processing as we can't determine which one to use 
Deceased Person
No correlated VA Profile ID

**VA Profile** 
No VA Profile account with ID
No Communication bio for that VA Profile account
No email address
No phone number 
Preference False
No Preference Set
No Preference Set / No Default Send *Note: don't currently have default send 

# Additional Info/Resources
-https://app.zenhub.com/workspaces/vanotify-5ea0ae59b51ccc3c83a8b65b/issues/department-of-veterans-affairs/notification-api/558

# Out of Scope
-

# Open Questions
-

**Comment by vikarus-tw** [comment] 2021-11-17 15:54
MPI and VAProfile test accounts that we used to verify intended behavior re: failure reasons / notification status updating

https://docs.google.com/spreadsheets/d/1KdjgA-8ZvoUQyQtBZfk8HEzSkvMNX7-rJ5zQMr6RiUE/edit#gid=0

**Comment by TWs-DevenS** [comment] 2021-12-10 16:06
All the AC's for this story have been identified. There were scenarios identified where the failures were marked as permanent failures however failure reasons where not being set correctly. These failure reasons were fixed, tested and reviewed  during frequent cross pairing (dev/test) sessions with the developers . ( Failure reasons for all MPI and VAProfile test account scenarios resulting in permanent failures outlined in the spreadsheet attached above were verified).

No separate documentation was deemed necessary for the notification status failure reasons as it was discussed that this type of information is primarily  necessary for operations support reasons and the support engineer would rather have the failure reason reason clearly available in the code where it will be kept current (with the code) at all times.

**Closed** 2021-12-16 17:07 UTC
