### ISSUE TITLE
[BUG] complaint_type placeholder not substituted in complaint emails

### ISSUE THREAD

**Issue by emilywu-tw** [department-of-veterans-affairs/notification-api#471] opened 2021-05-03 20:15 UTC
# Describe the Bug
Occasionally, complaint emails will not have the complaint_type filled out. MAY be happening for hotmail emails but don't have sufficient evidence.

# To Reproduce
Not really reproduce-able since it's dependent on the callback we get from SES

# Expected Behavior
Email should say "unknown complaint type" if complaint type is null

# Actual Behavior 
Complaint type is shown as placeholder: ((complaint_type))

# Screenshots
![Screen Shot 2021-05-03 at 4.12.07 PM.png](https://images.zenhubusercontent.com/5fd11ed22726999c86f797f7/b27a1e79-afb8-4234-bed4-8442381d860d)

**Comment by TWs-DevenS** [comment] 2021-05-18 18:27
Reviewed bug fix , 
instead of null an unknown complaint type will be displayed.
Test approach -the fix has been unit tested and passed. However since the issue is not easily recreated, logger event  to  track the occurrence of this scenario will be included.  i.e. if complaint type is a null then unknown complain type is the value displayed

**Closed** 2021-05-19 13:34 UTC
Labels: Bug, Email
