### ISSUE TITLE
Clear Celery chain instead of raise exception

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#2053] opened 2024-10-15 17:53 UTC
## User Story - Business Need
Celery tasks currently report as a failure when the task chain stops. This is both correct and incorrect! The chain termination for _expected_ reasons should not result in a failure, otherwise it would be a failure. We need to adjust expected failures to instead empty the request chain.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As** someone focusing on reliability of VA Notify
**I want** errors reserved for actual errors in the application
**So that** legitimate errors are not hidden in a sea of false errors

### Additional Info and Resources

- Celery [task request](https://docs.celeryq.dev/en/latest/userguide/tasks.html#task-request) has a `chain` parameter

## Acceptance Criteria

- [x] Tasks that result in permanent failure or preferences declined for expected reasons do not report a celery task failure
- [x] Technical failures and permanent failures that are in our generic catches still result in a task failure
- [x] "Expected reasons" are documented in the team repo so we can reference it in the future
- [x] Ticket to clean up all feature flags related to this work has been made
- [x] This work is added to the sprint review slide deck (key win bullet point and demo slide)

## QA Considerations

Working with the engineers to cover the expected reasons.

**Comment by k-macmillan** [comment] 2024-11-12 17:58
Reviewed the applicable locations where this could happen (tasks that are chained). Updated the tasks that are invoked to set the chain to `None` in the event of an expected failure. Created [documentation](https://github.com/department-of-veterans-affairs/vanotify-team/blob/main/Engineering/celery_chain_terminations.md) so there is less ambiguity regarding expected vs unexpected failures. Unit tests updated (things are no longer raising exceptions in some cases). All unit tests pass. Deploy passes regression.

Putting the ticket up for PR and creating a follow-on ticket to clear the feature flag that was created for this ticket.

**Comment by cris-oddball** [comment] 2024-11-12 19:54
PR approved and merged. Holding on perf for some manual validation for cases that the regression does not catch. Note that this is behind a feature flag, whic is only enabled in the lowers, not in Prod.

**Comment by cris-oddball** [comment] 2024-11-12 20:05
**QA TESTING IN PROGRESS**

The following no longer throw a celery error in the logs (Expected terminations):

- [ ]  No VA Profile Identifier
- [ ] No Contact Information
- [ ] Preferences declined (VA Profile) - validated by the regression, previously saw 6 logs per regression, now 0
- [ ] Individual is deceased
- [ ] Individual has opted out
- [ ] Message was undeliverable (provider/carrier declines to deliver)

The following are unexpected terminations, which should raise an error. However we will rely on unit tests for these.

-  Unable to parse a response from an integration (MPI, VA Profile, etc.)
- VA Notify raised an exception that was not expected/caught
- Validation errors with an integration, such as a 400 from VEText on a delivery status callback

**Comment by cris-oddball** [comment] 2024-11-12 21:44
Having a very hard time trying to raise any error for a deceased Veteran. 

- The [test spreadsheet](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv) indicates that certain users are deceased. Using Postman in Staging (to see the original behavior, since the code is not yet there) returns delivered statues so long as there is contact info, not a BeneficiaryDeceased exception.
- Searching for logs on 'deceased' in staging did turn up some logs from the MPI Lookup Lambda for deceased users, however I can send that user an sms and it returns a permanent-failure because the phone is invalid, not because the user is deceased.
> [DEBUG]	2024-11-11T10:01:46.574Z	4afc248b-97fa-5d33-a4a7-7b204ff965b5	MPI response body for VA Profile ID 1601278: {'resourceType': 'Patient', 'id': '1012826601V741386', 'deceasedDateTime': '2017-08-23', 'name': [{'use': 'official', 'family': 'LAWSON', 'given': ['RUSSELL', 'S']}], 'telecom': [{'system': 'email', 'value': 'testingvbms1@test.com', 'use': 'home'}], 'identifier': [{'system': 'urn:oid:2.16.840.1.113883.4.349', 'value': '1012826601V741386^NI^200M^USVHA^P'}, {'system': 'urn:oid:2.16.840.1.113883.3.42.10001.100001.12', 'value': '1045938782^NI^200DOD^USDOD^A'}, {'system': 'urn:oid:2.16.840.1.113883.4.349', 'value': '1601278^PI^200VETS^USDVA^A'}, {'system': 'urn:oid:2.16.840.1.113883.4.349', 'value': '600036163^PI^200CORP^USVBA^A'}, {'system': 'urn:oid:2.16.840.1.113883.4.349', 'value': '0000027865^PN^200PROV^USDVA^A'}]}

Without finding a user that can throw a BeneficiaryDeceased error, I'm not sure how to validate this ticket. It's safe enough to send it up to Prod since the Feature Flag is not enabled there but I need to discuss that with @k-macmillan  first.

**Comment by cris-oddball** [comment] 2024-11-12 22:50
Validation looks good, sending to Prod with no risk since the feature flag is not enabled there. Closing ticket as Done.

**Closed by cris-oddball** 2024-11-12 22:50 UTC
Labels: Notify, QA, Dev Reviewed, PM Reviewed, QA Reviewed, FF

**Comment by cris-oddball** [comment] 2024-11-13 14:13
Reviewed Datadog this morning on staging. The sudden drop-off in the celery errors shown in this screenshot occurs at the time of deployment to staging.
![Image](https://github.com/user-attachments/assets/e9b74f48-eabd-457c-b947-70b956e7f88b)
