### ISSUE TITLE
Remove Endpoints - send-pdf-letter

### ISSUE THREAD

**Issue by EvanParish** [department-of-veterans-affairs/notification-api#1163] opened 2023-03-21 19:04 UTC
## User Story - Business Need

In the effort to clean up our code we need to investigate and remove unused endpoints. This ticket is to take a look at the endpoints under `/service/<uuid:service_id>/send-pdf-letter` and remove the ones marked for removal. You can view the table of endpoints [here](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/VA%20Notify%20Endpoints.md).

### User Story(ies)
**As an** engineer
**I want** to clean up and reduce our codebase
**So that** it is easier to maintain and upgrade in the future.

### Additional Info and Resources
- [Endpoint Table](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/VA%20Notify%20Endpoints.md)
- [Endpoint Spreadsheet](https://docs.google.com/spreadsheets/d/18AfqlEOWlrnigauO57jA0VP3RMHTaP4luknqBxrcbuY/edit#gid=115873237)

## Engineering Checklist

- [x] Investigate the endpoints starting with `/service/<uuid:service_id>/send-pdf-letter` to make sure they aren't being used
- [x] Remove tests associate with those endpoints
- [x] Remove the code associated with those endpoints (if possible). Make sure not to remove any code used by other parts of the application.

## Acceptance Criteria

- When the designated code and tests have been removed, the application retains full functionality. 

## QA Considerations
- [x] The QA Regression Suite passes
- [x] The Cypress regression passes

## Potential Dependencies
- Make sure the removal of these endpoints doesn't affect the work Strike is doing.

**Comment by kalbfled** [comment] 2023-09-20 13:23
QA regression [passes](https://github.com/department-of-veterans-affairs/notification-api-qa/actions/runs/6249138210).  I contacted Nathan to inquire about running the Cypress regression.  Assuming that passes, development for this ticket is finished.  I will seek code review after Cris returns because we are not merging letter changes before then.

**Comment by cris-oddball** [comment] 2023-09-28 19:07
This is merged to master, but waiting for the ability to deploy to Perf for testing. 

Tag is cut for this point on master as v1.6.12-1163-ep-removal but tag is not yet pushed up to Perf.

**Comment by cris-oddball** [comment] 2023-09-28 20:27
Perf is stable, sending code to Perf for testing.

**Comment by cris-oddball** [comment] 2023-09-28 20:55
QA regression passes. 190 passed, 3 xfailed in 177.76s (0:02:57)

Closing ticket.

**Closed by cris-oddball** 2023-09-28 20:55 UTC
Labels: Tech Debt, Notify, QA, Dev Reviewed, PM Reviewed, QA Reviewed
