### ISSUE TITLE
Update flask-sqlalchemy to use new query interface

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#955] opened 2022-11-14 20:20 UTC
## User Story - Business Need

The code base contains many instances of using flask-sqlalchemy's [legacy query interface](https://flask-sqlalchemy.palletsprojects.com/en/3.0.x/queries/#legacy-query-interface).  Update the code to use the new interface.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)
**As a** developer,
**I want** to use the newer SQLAlchemy query interface
**So that** the code is ready to upgrade to SQLAlchemy >= 2.0.

**As a** developer,
**I want** to use the read-only database instance where appropriate
**So that** we maximize performance.

### Additional Info and Resources

Run `grep -rn \.query app/` (and in other directories) to find instances.

## Engineering Checklist

- [ ] All instance of the legacy query interface have been modified to use the new interface
- [ ] All queries use read-only where appropriate

## Acceptance Criteria

- [ ] All unit tests continue to pass

## QA Considerations
- [ ] regression passes
- [ ] work with Dev to test any specific areas of the app.

## Potential Dependencies
_Leave blank if n/a_

## Out of Scope

**Do not upgrade SQLAlchemy**.

**Comment by mjones-oddball** [comment] 2022-11-16 16:09
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/955?planning-poker) with Zenhub @cris-oddball @EvanParish @ianperera @jakehova @k-macmillan @kalbfled @trevor2718 @ldraney

**Comment by mjones-oddball** [comment] 2023-02-28 21:01
@kalbfled Is this different from the sqlalchemy upgrade work and/or are there any dependencies between the two items? @k-macmillan this one is a little out of my realm to review, but it looks pretty slim - can you help me understand what needs to be added?

**Comment by kalbfled** [comment] 2023-05-03 19:03
@mjones-oddball This is a deprecation issue.  We upgraded from SQLAlchemy 1.3.x to the newest 1.4.x, which supports a "legacy" syntax that SQLAlchemy >= 2.0 no longer supports.

**Comment by cris-oddball** [comment] 2023-08-09 13:44
@kalbfled @mjones-oddball @k-macmillan Is this necessary to upgrade SQLAlchemy? We recently discussed needing to fix the SAWarning errors to be able to upgrade but do we need this too?

**Comment by kalbfled** [comment] 2023-08-09 16:24
Yes, this is necessary.  SQLAlchemy 2.0 does not support the older syntax.

**Comment by mjones-oddball** [comment] 2023-08-15 21:39
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/955?planning-poker) with Zenhub @babyjunior56 @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by mjones-oddball** [comment] 2023-11-27 16:56
this is a duplicate of #1538

**Closed by mjones-oddball** 2023-11-27 16:56 UTC
Labels: Tech Debt, Notify, QA, Dev Reviewed, PM Reviewed, QA Reviewed
