### ISSUE TITLE
Comp and Pen: Update Send Notification to Use Batch Write

### ISSUE THREAD

**Issue by EvanParish** [department-of-veterans-affairs/notification-api#1707] opened 2024-03-26 21:26 UTC
## User Story - Business Need
Currently, individual update_item calls are made within a loop, which can lead to inefficiencies, especially when dealing with large datasets. The suggested solution is to implement batch_writer, which allows for batching of update operations. This change aims to optimize the process of updating DynamoDB records by reducing the number of database update calls and improving overall performance.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** VA Notify engineer 
**I want** to update the method of updating items in our DynamoDB table to use batch_writer 
**So that** I can optimize the process, reduce API overhead, and improve performance when handling updates for these scheduled SMS sends. 

### Additional Info and Resources

- boto3 docs for [batch_writer](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb/table/batch_writer.html) 
- aws [BatchWriteItem docs](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html)
  - note update can't be used with BatchWriteItem

[crontab change](https://github.com/department-of-veterans-affairs/notification-api/blob/5504543d6c9b99cbe706ea7524dbd39cd59f1f90/app/config.py#L336) only requires adding `minute='*/2'`

## Engineering Checklist

- [x] Update the cron for this to execute every 2 minutes instead of every 1 minute to give time for processing and updates.
- [x] If necessary, complete the prerequisite infra permissions change described in a comment [here](https://github.com/department-of-veterans-affairs/vanotify-infra/blob/master/cd/application-infrastructure/roles.tf#L238).  The role needs dynamodb:BatchWriteItem and dynamodb:PutItem permissions.  Remove dynamodb:UpdateItem permission.
- [x] Move the update_item calls to our dynamodb out of the loop
- [x] Update the update_item calls to our dynamodb [here](https://github.com/department-of-veterans-affairs/notification-api/blob/1703-twilio-error-fix/app/celery/scheduled_tasks.py#L343) to use batch_writer instead of doing updates individually
  - we won't be able to use update anymore, so we'll need to use put_item instead in the batch_write
- [x] Update unit testing as needed

## Acceptance Criteria

- When the scheduled sms sends for Comp and Pen messages are sent we use batches to update the dynamodb table instead of updating individual records.

## QA Considerations
- Review testing to see that dynamoDb was updated in batches. Work with developer as necessary (which means the dev will need to involve QA when testing in a deployed environment)

**Comment by mjones-oddball** [comment] 2024-03-29 20:46
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1707?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @MackHalliday @mchlwellman

**Comment by k-macmillan** [comment] 2024-04-01 15:23
In regards to the change from 1 -> 2 minutes:
- [Celery Beat](https://docs.celeryq.dev/en/stable/userguide/periodic-tasks.html#beat-entries)
- [relevant crontab](https://github.com/department-of-veterans-affairs/notification-api/blob/5504543d6c9b99cbe706ea7524dbd39cd59f1f90/app/config.py#L336)

**Comment by mchlwellman** [comment] 2024-04-04 21:57
Today - 

- Updated celery beat schedule
- Updated single row update to batch

Tomorrow -

- Add unit tests
- Deploy and test

**Comment by cris-oddball** [comment] 2024-04-09 17:36
Tested this by deploying to Perf with a seeded cache. The test cases expected to be sent were sent, the ones not expected to be sent were not. Regression passed.

APM tracing not configured to show DynamoDB and debug logging not enabled in Perf, so more conclusive logs or tarces were not available.

**Comment by cris-oddball** [comment] 2024-04-10 16:23
This code was previously tested on Perf. That said it would be good to retest. The cron job should run next on April 13, 1PM ET, which is Saturday. I'd like to queue up the DB to be prepped for that cron job and see the results on Monday, prior to closing this ticket. I want to at least think about that - it would mean missing the API release. Will leave a comment at EOD with my decision.

CI/CD Deployment is [paused](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/8633207530) for merge to Release and deploy Release to staging.

**Comment by cris-oddball** [comment] 2024-04-10 17:53
OK, so the cron will next run on the 21st, so I do need to finish out the deploy and close the ticket. Will do so by EOD.

**Comment by cris-oddball** [comment] 2024-04-10 19:21
The current state of things is 

- the staging regression [failed](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/8633207530) in the pipeline because it took a very long time for a v2 sms to get to a delivered state
- the regression cannot be rerun until a GitHub incident is cleared
- hopefully the regression can just be re-run and then it can proceed through the pipeline
- discussed w/ Lucas a possible way to bypass the regression for issues that have nothing to do with us (long delivery times)

On hold until I can re-run that staging regression.

**Comment by cris-oddball** [comment] 2024-04-10 22:57
Was able to re-run staging regression. Will check in the morning on the results.

**Comment by cris-oddball** [comment] 2024-04-10 23:05
Staging regression passed. Closing ticket as Done.

**Closed by cris-oddball** 2024-04-10 23:05 UTC
Labels: Notify, QA, Dev Reviewed, PM Reviewed, QA Reviewed
