### ISSUE TITLE
Update Celery Retry Policies

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1226] opened 2023-04-19 17:46 UTC
## User Story - Business Need
The recent issue where Twilio was down for several hours brought to light that we hammer ourselves while trying to handle the requests coming in. We want to release some of the pressure on our celery service by having a better retry policy that takes into account a service may be down for a day. 

Increase the total retry time to 24 hours and use a method to backoff the requests (either through an equation or some other method). We should retry frequently at first, then back off after a reasonable amount of time. Ensure jitter is used.

- [ ] Discuss the retry frequency when known with QA

### User Story(ies)
**As** VA Notify
**I want** retries that make sense when a system is down
**So that** we are not needlessly hammering our service

### Additional Info and Resources
- [Celery retry](https://docs.celeryq.dev/en/v4.4.7/userguide/tasks.html#retrying)
- [Why Jitter Matters](https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/)
- [How Celery does jitter](https://github.com/celery/celery/blob/89815ca617217dc2c2fb896848ee877aec0bc69e/celery/utils/time.py#L374)
  - Essentially means it chooses a random value between 1 and the maximum current backoff value

## Engineering Checklist
- [x] Retries will happen for up to 24 hours
- [x] [retry_backoff](https://docs.celeryq.dev/en/stable/userguide/tasks.html#Task.retry_backoff) set to True
- [x] [retry_backoff_max](https://docs.celeryq.dev/en/stable/userguide/tasks.html#Task.retry_backoff_max) set to value specified below
~- [ ] [retry_jitter](https://docs.celeryq.dev/en/stable/userguide/tasks.html#Task.retry_jitter) set to True~ Defaults to `True`
- [x] Create a [support ](https://github.com/department-of-veterans-affairs/vanotify-team/tree/master/Support)md doc in vanotify-team repo so we know what the retry policy is in which circumstance, please pair with Product to ensure documentation is understandable for clients in case questions arise

A simple average retry time (negating the ramp up in backoff) in hours can be calculated with the following (view on [github](https://github.com/department-of-veterans-affairs/notification-api/issues/1226)):
```math
AvgRetryMaxLength = \frac{(MaxRetries - \lceil log_2(RetryBackoffMax) \rceil) \times RetryBackoffMax}{7200}
```
MaxRetries of 100 and RetryBackoffMax set to 300 would yield $3.791\overline{6}$ $AvgRetryMaxLength$ hours of retries.

We can easily reverse this to calculate how many $MaxRetries$ are necessary to get to an average 24 hours of retries: 585
```math
MaxRetries = \frac{hours \times 7200}{RetryBackoffMax} + \lceil log_2(RetryBackoffMax) \rceil
```

### Retry list (in seconds)
  - [x] deliver_sms - 60
  - [x] deliver_email - 60
  - [x] lookup_contact_info - 60
  - [x] lookup_recipient_communication_permissions - 60
  - [x] lookup_va_profile_id - 60
---
  - [x] process_pinpoint_results - 300
  - [x] process_delivery_status - 300
  - [x] process_pinpoint_inbound_sms - 300
---
  - [x] send_delivery_status_to_service - 3600
  - [x] send_complaint_to_service - 3600
  - [x] send_complaint_to_vanotify - 3600
  - [x] send_inbound_sms_to_service -3600

## Acceptance Criteria
Retries happen for up to 24 hours and the retry policy matches what is specified in this ticket.

## QA Considerations
- [ ] check logs after deploy to determine that retries are happening as described in AC. Developer to provide intervals expected when the ticket goes to PR.

## Potential Dependencies
We should have the celery upgrade done prior to working this. We do not want to implement something that Celery 5.x already has or have to refactor because what we come up with is not compatible with 5.x.

**Comment by mjones-oddball** [comment] 2023-06-07 13:25
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1226?planning-poker) with Zenhub @cris-oddball @EvanParish @justaskdavidb2 @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by k-macmillan** [comment] 2023-07-13 20:41
@mjones-oddball [Documentation](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Support/retry_policy.md). I suggest only showing services the table 😃 

This work is done but needs testing. Tomorrow evening I will deploy the branch to dev with a small tweak to force email failures so we can ensure everything is working as expected.

**Comment by k-macmillan** [comment] 2023-07-14 03:32
Read from the bottom up. Anything under 10 seconds appears sketchy. I believe that's by design with Celery and not a concern. Any retry > 10 seconds is behaving exactly as expected.
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/bdfcdf68-a5b0-482c-bec3-08519e21ff5c)

**Comment by k-macmillan** [comment] 2023-07-14 15:20
To trigger these retries I had to not call `self.retry()`, it has to come from a tuple of approved automatic retry Exceptions. That's reasonable and can be easily fixed.

**Comment by k-macmillan** [comment] 2023-07-17 14:27
Adding the necessary parameters was not an issue, but it requires extensive unit test overhaul. This was not expected. The method appears to throw a type error which means I cannot verify the `AutoRetryException` is raised, which was how I expected to verify a retry. Previously the code called `task.retry()`, which raised a `celery.exceptions.Retry` error. 

At this point I need to find out how to detect it and then create a method that can be used across all of our celery auto retry tests.

**Comment by k-macmillan** [comment] 2023-07-20 15:01
Was able to make it through most of the unit test failures. Autoretries are handled so differently that it required a complete rework. Working through the last few tests now.

**Comment by cris-oddball** [comment] 2023-07-20 20:01
For this ticket, we will deploy it to Perf and Staging to let it sit there and observe everything is working fine (as per discussion with @k-macmillan). This will not make it into next week's deploy.

**Comment by k-macmillan** [comment] 2023-07-21 14:08
The work is done, we just need to be thorough in testing/review. The PR was put up for review but as Cris mentioned we're going to check this over the next week to ensure nothing slipped. This ticket involved a surprising amount of refactoring.

**Comment by k-macmillan** [comment] 2023-07-21 20:13
PR has been merged. We're now going to let it sit, checking Datadog daily for any issues in perf/staging.

**Comment by cris-oddball** [comment] 2023-07-21 20:15
Keeping this in the QA lane - it is deploying to Perf. Will send it up to Staging after the staging release next Tuesday to let it sit there.

**Comment by cris-oddball** [comment] 2023-07-21 20:35
Perf regression: 130 passed, 2 skipped, 3 xfailed in 129.36s (0:02:09

Will test that again on Monday, when the VA's caches are cleared on those routes.

**Comment by cris-oddball** [comment] 2023-07-21 22:57
HUZZAH
Ran the perf regression after deploying Infra 3x, 
```
130 passed, 2 skipped, 3 xfailed in 143.80s (0:02:23) 
```
which is a minute longer than a run where the lookup info is cached on the VA's side. Checked the logs and found...

```
[2023-07-21 22:38:03,918: INFO/ForkPoolWorker-4] Task lookup-recipient-communication-permissions[7c6b22e8-737c-41a4-80de-3e851540aa7c] retry: Retry in 0s: AutoRetryException('Found VAProfileRetryableException, autoretrying...', VAProfileRetryableException('VA Profile returned RequestException while querying for VA Profile ID'), ('VA Profile returned RequestException while querying for VA Profile ID',))

[2023-07-21 22:38:04,218: INFO/ForkPoolWorker-4] Task lookup-recipient-communication-permissions[cb0fd2b0-e87f-4900-8622-6a50853b9ef4] retry: Retry in 1s: AutoRetryException('Found VAProfileRetryableException, autoretrying...', VAProfileRetryableException('VA Profile returned RequestException while querying for VA Profile ID'), ('VA Profile returned RequestException while querying for VA Profile ID',))
```

Since the tests passed, the notification for that must have reached the expected status as the tests looped through the exponential backoff so this is working for the regression! :tada:

@k-macmillan

**Comment by cris-oddball** [comment] 2023-07-24 14:41
Sweet, ran a regression against Perf this morning after the weekend, the calls to lookup communication items would by now not be cached on the VA side, and the tests completed in 2 minutes, as expected. This confirms the above comment!
`130 passed, 2 skipped, 3 xfailed in 128.16s (0:02:08)`

**Comment by tabinda-syed** [comment] 2023-07-24 14:52
Team will move this into Staging until next release. We are closing this ticket, but we will keep an eye on things and Cris/team will create bugs as items are seen. No additional eng. work needed unless there's any issue.

**Closed by tabinda-syed** 2023-07-24 14:53 UTC
Labels: Notify, QA, Dev Reviewed, PM Reviewed, QA Reviewed, Off-track
