### ISSUE TITLE
BUG: Service Callback does not include source payload

### ISSUE THREAD

**Issue by jakehova** [department-of-veterans-affairs/notification-api#1201] opened 2023-04-07 16:20 UTC
## Description
Service Callbacks have a feature of including a source payload in the webhook request.  If the "include_provider_payload" flag is set to true for the callback, then the webhook should include the source payload in the POST request to the webhook endpoint.  If it is set to false, then the source payload should NOT be included in the POST request. 

The bug found was that regardless of the value of "include_provider_payload", no source payload was included in the POST request to the webhook endpoint.

**Comment by cris-oddball** [comment] 2023-04-07 22:15
Code merged into master and deployed to Perf.
The provider_payload is now populated when set to True.

![Screen Shot 2023-04-07 at 4.12.57 PM.jpg](https://images.zenhubusercontent.com/630696b479f5cca51e546872/2a7a3d3f-e5a0-4c80-b749-17484f9021c6)

However, new behavior is that my callback is being hit for every message, whether email through SES or sms through Pinpoint. Noticed this when I ran the regression. The regression was run this morning and the my callback was not hit for that.

![Screen Shot 2023-04-07 at 4.14.12 PM.jpg](https://images.zenhubusercontent.com/630696b479f5cca51e546872/eff55f6b-20bf-4aa4-a802-a4c19d4b4da7)

![Screen Shot 2023-04-07 at 4.14.45 PM.jpg](https://images.zenhubusercontent.com/630696b479f5cca51e546872/a734c116-6933-499f-b6fb-ded2f595b189)

Will bring up with team on Monday.

**Comment by cris-oddball** [comment] 2023-04-10 17:04
This is working as designed. Deployed the code to staging (manually) and closing ticket.

**Closed by cris-oddball** 2023-04-10 17:04 UTC
Labels: bug, Notify, QA

**Comment by mjones-oddball** [comment] 2023-04-10 17:25
@jakehova @k-macmillan Can you please point this since it's closed? CC @tabinda-syed
