### ISSUE TITLE
Load Testing: Measurements - Celery - deliver_sms

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#966] opened 2022-11-28 23:22 UTC
## Issue
We do not currently know how long "[deliver_sms](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/celery/provider_tasks.py#L20)" takes to complete. Without knowing how long it takes to complete we are unable to identify abnormalities or expected throughput for our system. 

Find and implement a way to measure how long the method takes to process so we can create metrics. This could take many forms, but the key is to identify the time difference between when the method was called and when the method responds.

## Checklist
- [x] Measurement of time for each call to the method is stored somewhere
  - [ ] Preferable to know if the method ran clean or if it hit an error (but not necessary for MVP)

**Comment by mjones-oddball** [comment] 2022-11-29 23:13
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/966?planning-poker) with Zenhub @cris-oddball @EvanParish @ianperera @jakehova @k-macmillan @kalbfled @ldraney @trevor2718

**Comment by ldraney** [comment] 2022-12-07 07:51
Goal: Find a way to aggregate the logs similar to this output:![Screenshot 2022-12-02 134132.png](https://images.zenhubusercontent.com/6361638d438b9c8e844e2b23/ee222445-62cd-48eb-8947-227149682482)

**Comment by ldraney** [comment] 2022-12-07 08:11
I'm currently talking to Cris to make sense of the situation with her expertise and my naivety.  So first, the relevent deliver_sms function is mentioned in:
./tests/app/user/test_rest_verify.py
./tests/app/public_contracts/test_POST_notification.py
./tests/app/celery/test_provider_tasks.py
./tests/app/celery/test_tasks.py
./tests/app/v2/notifications/test_post_notifications.py
./tests/app/notifications/test_process_notifications.py
./tests/app/notifications/rest/test_send_notification.py
Whereas in app/celery/provider_tasks.py it is defined and in app/celery/tasks.py it is being used...
It's also in app/notifications/process_notifications.py 

Also the end point notifications/sms is referred to in the following files:
./load_testing/send_sms_load_test.py
./lambda_functions/user_flows/steps.py
./documents/openapi/openapi.yaml
./documents/openapi/openapi-with-push.yaml
./tests/app/public_contracts/test_POST_notification.py
./tests/app/v2/notifications/test_post_notifications.py
./tests/app/notifications/rest/test_send_notification.py
./scripts/postman/notification-api.postman_collection.json
./app/v2/notifications/notification_schemas.py

**Comment by ldraney** [comment] 2022-12-07 08:12
The logs that Kyle wants me to get are from cloudwatch, so to get access to those logs through datadog I need to reference [this documentation:](https://docs.datadoghq.com/containers/amazon_ecs/logs/?tab=linux)

**Comment by ldraney** [comment] 2022-12-07 08:36
Another relevant file:
`/notification-api/.github/workflows/load-test-sms-response-time.yaml`

**Comment by ldraney** [comment] 2022-12-07 09:32
Perhaps the first step forward is adding prod-notification-api-log-group to [datadogs Logs](https://docs.datadoghq.com/logs/log_collection/?tab=host)
My blocker here is I want to see our AWS log groups from my own CLI rather than GH Actions, since learning about our infra through Actions is a pain.
I also need to learn how to enable Datadogs Collection and Integrations with our desired log group...
I can see that we already have some log groups with datadog in `vanotify-infra/cd/application-infrastructure/monitoring.tf`, but I can't find a way to access the groups from the Datadog dashboard.

**Comment by ldraney** [comment] 2022-12-07 09:46
Another potentially relevant/useful file is [Send AWS Services Logs With The Datadog Lambda Function](https://docs.datadoghq.com/logs/guide/send-aws-services-logs-with-the-datadog-lambda-function/?tab=awsconsole)

**Comment by ldraney** [comment] 2022-12-07 10:05
The flask POST response that is going to our log group on AWS is associated with these files:
```
./tests/app/public_contracts/test_POST_notification.py
./tests/app/v2/notifications/test_post_notifications.py
./tests/app/notifications/rest/test_send_notification.py
```

**Comment by cris-oddball** [comment] 2022-12-07 15:47
@ldraney anything in `./tests/app/` are unit tests, which all use mocks. 

The API route in question is `v2/notifications/sms` - probably a good place to start is with the Postman collection, and that endpoint, noting that it takes a little effort to get the Postman collection set up with the correct env vars and an api key to be able to make calls. Any dev should be able to assist (or I can).

**Comment by ldraney** [comment] 2022-12-08 07:21
The most helpful and relevant Datadog docs are the following:

- 

Essentially for monitoring, "[to monitor your ECS Fargate tasks with Datadog](https://vanotify.ddog-gov.com/integrations/aws-fargate), run the Agent as a container in same task definition as your application container."

Essentially for log aggregation, we either need to set up an [ECS file](https://docs.datadoghq.com/containers/amazon_ecs/logs/?tab=linux#ecs-file) or follow the guide to [Docker Log Collection](https://docs.datadoghq.com/containers/docker/log/?tab=containerinstallation)

**Comment by ldraney** [comment] 2022-12-08 10:09
We already have the above document applied to `notification/api/cd/application-deployment/dev/vaec-celery-task-definition.json  `

**Comment by ldraney** [comment] 2022-12-08 10:13
Here is the exact [Terraform guide](https://docs.datadoghq.com/logs/guide/forwarder/#terraform) to set up the Lambda Forwarder to get the logs to Datadog.

**Comment by ldraney** [comment] 2022-12-08 10:32
The first part of the Terraform guide was complete, in that the dd_api_key was set up.  
But we do not have the datadog-forwarder lambda set up yet!

**Comment by ldraney** [comment] 2022-12-08 11:01
Made first changes to branch `966-deliver-sms-data`, I'm not sure if this lambda should be deployed from utility-infrastructure or another directory... though it probably doesn't matter.

**Comment by ldraney** [comment] 2022-12-08 11:54
I'm getting close to having the forwarder deployed!  Now I'm battling the fact that `utilities-infrastructure `never had a `development.tfvars` file!  So, I'll probably have to go through these .tf files and set one up myself.

**Comment by ldraney** [comment] 2022-12-18 04:50
Back on this issue.  I recently found this command produced some logs with the desired information:

But, I need to parse out what we need.  So, I'm looking at this [aws documentation for log queries](https://docs.aws.amazon.com/en_us/AmazonCloudWatch/latest/logs/CWL_QuerySyntax.html).

**Comment by ldraney** [comment] 2022-12-18 06:55
I wrote a query that gives the desired output in the CloudWatch Logs Insights console:

But, the problem is still being confined to the AWS GUI; and the point of this project is to create useful metrics.  So, first I will make a successful CLI query; A successful CLI query output is a key indicator for this project, because then we can make metrics from a python script.  

Then final leg of this project would be: can and how does Datadog make this easier?

**Comment by ldraney** [comment] 2022-12-19 09:33
The following script will get the desired logs into a file called query-results.json.  (I'm not really sure if the output is json but looks like it.)

#!/bin/bash


aws logs start-query \
--start-time $((`date -d "2022-12-07 00:00:00" -u +"%s"` * 1000)) \
--end-time $((`date -d "2022-12-19 00:00:00" -u +"%s"` * 1000)) \
--limit 4 \
--log-group-name "prod-notification-api-log-group" \
--query-string 'fields @message 
| filter @message like "POST" 
| filter @message like "INFO" 
| filter @message like "sms" 
| filter @logStream like "ecs/notification-api" ' \
--region us-gov-west-1 \
--output text > /tmp/query.txt

echo "sleeping three seconds..."
sleep 3

aws logs get-query-results \
	--region us-gov-west-1 \
	--query-id "$( cat /tmp/query.txt )"

**Comment by ldraney** [comment] 2022-12-22 16:37
Output looks like this:
```
2022-12-18	23:15:16,091	https://api.notifications.va.gov/v2/notifications/sms	201	0.16541"	
2022-12-18	23:00:24,659	https://api.notifications.va.gov/v2/notifications/sms	201	0.14184"	
2022-12-18	23:00:17,470	https://api.notifications.va.gov/v2/notifications/sms	201	0.16029"	
2022-12-18	22:45:28,809	https://api.notifications.va.gov/v2/notifications/sms	201	0.15200"	
2022-12-18	22:30:23,311	https://api.notifications.va.gov/v2/notifications/sms	201	0.15434"	
2022-12-18	22:01:56,075	https://api.notifications.va.gov/v2/notifications/sms	201	0.13331"	
2022-12-18	22:01:32,398	https://api.notifications.va.gov/v2/notifications/sms	201	0.12127"	
```
And the script can be adjusted for different log groups, most recent, how many logs you want, etc.
outputs to `/tmp/metric-data.txt`

**Comment by cris-oddball** [comment] 2022-12-22 17:11
@ldraney I think the task asks to report on celery, not the api, "how long "[deliver_sms](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/celery/provider_tasks.py#L20)" takes to complete". 

The above metrics are pretty much what Locust is already providing me for the API route call.  We need insight into how Celery (the queue) is performing.  Could be as easy as changing this line to point to celery ` filter @logStream like "ecs/notification-api" ' \` 

I believe there are ways to get those celery metrics into DD directly (Google says so, anyhoo).

**Comment by ldraney** [comment] 2023-01-09 07:09
@cris-oddball    Good catch!  I changed the filter to ecs/notification-celery and deleted POST and INFO filters, and got useful data! 

However, you're right that DD is the way to go, so I'll be focusing on that for the next sprint and put this in our glossary meanwhile.

**Comment by ldraney** [comment] 2023-01-09 07:22
I updated our [Teams Repo](https://github.com/department-of-veterans-affairs/vanotify-team/tree/master/Engineering/DevOps/aws/log_metric_scripts) (AKA the glossary, right?)  And now am hoping to close this ticket.

**Comment by cris-oddball** [comment] 2023-01-09 15:15
@ldraney you can set it to Done, but not Closed, please.

**Closed** 2023-01-09 22:28 UTC
Labels: Notify, monitoring
