### ISSUE TITLE
Delivery Status Callbacks: VA Profile lookup failures

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#1800] opened 2024-05-07 18:00 UTC
## User Story - Business Need
We want to ensure all critical points of failures are shared via delivery status callbacks with our clients, so they are empowered to analyze and manage their notifications. Recently, we discovered that contact info lookup errors were not triggering callbacks.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** VA Business Line
**I want** to know if my notification fails due to a lookup error with VA Profile
**So that** I know which Veterans did not receive notifications as a result

### Additional Info and Resources

- Evan checked the prod logs and was able to see callbacks being triggered for an MPI lookup error, but did not see evidence of callback when contact information was not found in VA Profile. It's unclear how many other VA Profile related errors are or are not being sent through callback. Preference-declined is an example of one that is sent today.

## Acceptance Criteria

- [x] Callbacks are triggered for VA Profile Lookup Errors
> GIVEN callbacks are enabled for a service
> WHEN a notification from that service enters a final error state due to a VA Profile contact or preference lookup failure
> THEN a delivery status callback should be triggered to the appropriate destination assigned to that callback

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._
- Will need a vaprofiel id with no contact info (plenty in perf/staging to choose from, see kafka e2e testing to grab one)
- Will need access to a callback
- Work w/ dev on testing strategy

**Comment by mjones-oddball** [comment] 2024-05-07 18:21
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1800?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @MackHalliday @mchlwellman

**Comment by npmartin-oddball** [comment] 2024-05-08 16:02
Surface concerns, and early, should they manifest.

**Comment by kalbfled** [comment] 2024-07-30 22:09
This might be a fairly straight-forward fix.  The `lookup_va_profile_id` task contains a "try" with three "except" blocks--1 for retryable exceptions and 2 for non-retryable exceptions.  Only one of the blocks for non-retryable exceptions calls `check_and_queue_callback_task`.  See [here](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/celery/lookup_va_profile_id_task.py#L81).

**Comment by kalbfled** [comment] 2024-07-31 15:36
There are multiple code paths that result in HTTP requests to VA Profile, and changes might need to address both of them.

In the file app/notifications/process_notifications.py:
- Line 187 queues the task [lookup_va_profile_id](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/celery/lookup_va_profile_id_task.py#L32), which uses [MPIClient](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/va/mpi/mpi.py#L74).  See the comment above.
- Line 252 declares the function `send_to_queue_for_recipient_info_based_on_recipient_identifier`, which queues the task [lookup_contact_info](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/celery/contact_information_tasks.py#L25), which uses [VAProfileClient](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/va/va_profile/va_profile_client.py#L31).  The lookup_contact_info task does not contain any calls to `check_and_queue_callback_task`.

**Comment by kalbfled** [comment] 2024-08-02 14:20
I am mostly finished with this ticket, but I need changes for #1896 merged before I can finish it.

**Comment by kalbfled** [comment] 2024-08-05 13:34
I'm modifying unit tests for contact_information_tasks.py.  This is simple enough, but the database isn't getting properly cleaned up for reasons I don't yet understand.

**Comment by kalbfled** [comment] 2024-08-05 21:35
I replaced the "notification" fixture in test_contact_information_tasks.py with use of the sample_notification fixture in app/conftest.py.  I expected this to fix the problem with the test database not being cleaned up properly, but the problem persists.  This, and the still outstanding changes for #1896, are the reasons this ticket is carrying over to the next spring.  I anticipate wrapping it up tomorrow.

**Comment by kalbfled** [comment] 2024-08-06 17:15
After deleting and recreating my database container, I do not get any db artifacts when I run tests.  I'm still waiting on #1896.

**Comment by cris-oddball** [comment] 2024-08-08 16:29
PR approved and merged and deployed to Perf for testing.
Regression failed on notification taking too long to get to a delivery status
`"notification ce64ae86-3436-49a3-9898-2ada65039865 took 395.224435s total time to reach delivered status - pinpoint"`

rerunning regresision.

**Comment by cris-oddball** [comment] 2024-08-08 16:37
second regression failing trying to create a webhook
` 2024-08-08T16:34:19.4656265Z E       AssertionError: Expected status of Created. Received 500.`

**Comment by cris-oddball** [comment] 2024-08-08 16:44
3rd time is the charm. Now I can add back in a callback and start validating this.

**Comment by cris-oddball** [comment] 2024-08-08 17:56
**QA TESTING IN PROGRESS**

- [ ] TC01 - email sent to a recipient_identifier that has no contact information for email results in a callback that includes the status and status reason as permanent-failure and a message that there is no contact info. This is also the final delivery status.
- [ ] TC02 - sms sent to a recipient_identifier via Pinpoint that has no contact information for mobile results in a callback that includes the status and status reason as permanent-failure and a message that there is no contact info. This is also the final delivery status.
- [ ] TC03 - sms sent to a recipient_identifier via Twilio that has no contact information for mobile results in a callback that includes the status and status reason as permanent-failure and a message that there is no contact info. This is also the final delivery status.
- [ ] TC03 - SMS Default Send True w/ VAPROFILEID w/o Comm Items preferences results in a callback that includes the status reason as delivered
- [ ] TC04 - SMS Default Send False w/ VAPROFILEID w/o Comm Items preferences results in a callback that includes the status reason as preferences-declined
- [ ] TC05 - SMS Default Send True w/ VAPROFILEID w/ Allowed Comm Items results in a callback that includes the status reason as delivered
- [ ] TC06 - SMS Default Send False w/ VAPROFILEID w/ Allowed Comm Items results in a callback that includes the status reason as delivered
- [ ] TC07 - SMS Default Send True w/ VAPROFILEID w/ Disallowed Comm Items results in a callback that includes the status reason as preferences-declined
- [ ] TC08 - SMS Default Send False w/ VAPROFILEID w/ Disallowed Comm Items results in a callback that includes the status reason as preferences-declined
- [ ] TC09 - EMAIL Default Send True w/ VAPROFILEID w/o Comm Items preferences results in a callback that includes the status reason as delivered
- [ ] TC10 - EMAIL Default Send False w/ VAPROFILEID w/o Comm Items preferences results in a callback that includes the status reason as preferences-declined
- [ ] TC11 - EMAIL Default Send True w/ VAPROFILEID w/ Allowed Comm Items results in a callback that includes the status reason as delivered
- [ ] TC12 - EMAIL Default Send False w/ VAPROFILEID w/ Allowed Comm Items results in a callback that includes the status reason as delivered
- [ ] TC13 - EMAIL Default Send True w/ VAPROFILEID w/ Disallowed Comm Items results in a callback that includes the status reason as preferences-declined
- [ ] TC14 - EMAIL Default Send False w/ VAPROFILEID w/ Disallowed Comm Items results in a callback that includes the status reason as preferences-declined

**Comment by cris-oddball** [comment] 2024-08-12 20:05
TESTING NOTES:
[Spike](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/explicit_preference_logic.md) for Communication Preferences

[Ticket](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/notification-api/1227) that implemented the feature (look for the scenarios in the AC)

**Comment by npmartin-oddball** [comment] 2024-08-13 15:21
Adjusting pointing due to changes in ticket scope.

**Comment by cris-oddball** [comment] 2024-08-13 15:38
Team agreed that this need to be hammered out and working in all areas that a callback is expected to be sent in.

**Comment by kalbfled** [comment] 2024-08-13 16:24
In addition to Celery tasks that query VA Profile (which I already modified), I have identified additional Celery tasks in the chain of task used to send a notification.  I am going to audit each of these and ensure that callbacks are queued whenever a notification reaches a final state.

**Comment by cris-oddball** [comment] 2024-08-15 19:44
PR Approved, Merged and sent to Perf for testing.

**Comment by cris-oddball** [comment] 2024-08-15 19:46
**QA TESTING IN PROGRESS**

- [ ] ~~TC01 - email sent to a recipient_identifier that has no contact information for email results in a callback that includes the status and status reason as permanent-failure and a message that there is no contact info. This is also the final delivery status.~~
- unable to locate a vaprofileid that does not have an email address, but the code goes into the same code block.
<br></br>

- [ ] TC01 - sms sent to a recipient_identifier via Pinpoint that has no contact information for mobile results in a callback that includes the status and status reason as permanent-failure and a message that there is no contact info. 
Callback for `2e64509a-7907-458d-9cfb-6e1244df3ad2` includes
> 'status': 'permanent-failure',  'status_reason': 'No contact info found from VA Profile'

- [ ] TC02 sms sent to a recipient_identifier via Twilio that has no contact information for mobile results in a callback that includes the status and status reason as permanent-failure and a message that there is no contact info. This is also the final delivery status.
Callback for `3c57bf52-bcb5-4ea5-a892-26d29026cca2` includes
> 'status': 'permanent-failure',  'status_reason': 'No contact info found from VA Profile'

- [ ] TC03 - SMS Default Send True w/ VAPROFILEID w/o Comm Items preferences results in a callback that includes the status reason as delivered
- [ ] TC04 - SMS Default Send False w/ VAPROFILEID w/o Comm Items preferences results in a callback that includes the status reason as preferences-declined
- [ ] TC05 - SMS Default Send True w/ VAPROFILEID w/ Allowed Comm Items results in a callback that includes the status reason as delivered
- [ ] TC06 - SMS Default Send False w/ VAPROFILEID w/ Allowed Comm Items results in a callback that includes the status reason as delivered
- [ ] TC07 - SMS Default Send True w/ VAPROFILEID w/ Disallowed Comm Items results in a callback that includes the status reason as preferences-declined
- [ ] TC08 - SMS Default Send False w/ VAPROFILEID w/ Disallowed Comm Items results in a callback that includes the status reason as preferences-declined
- [ ] TC09 - EMAIL Default Send True w/ VAPROFILEID w/o Comm Items preferences results in a callback that includes the status reason as delivered
- [ ] TC10 - EMAIL Default Send False w/ VAPROFILEID w/o Comm Items preferences results in a callback that includes the status reason as preferences-declined
- [ ] TC11 - EMAIL Default Send True w/ VAPROFILEID w/ Allowed Comm Items results in a callback that includes the status reason as delivered
- [ ] TC12 - EMAIL Default Send False w/ VAPROFILEID w/ Allowed Comm Items results in a callback that includes the status reason as delivered
- [ ] TC13 - EMAIL Default Send True w/ VAPROFILEID w/ Disallowed Comm Items results in a callback that includes the status reason as preferences-declined
- [ ] TC14 - EMAIL Default Send False w/ VAPROFILEID w/ Disallowed Comm Items results in a callback that includes the status reason as preferences-declined

**Comment by cris-oddball** [comment] 2024-08-15 20:24
All tests pass - sending up to Prod and closing ticket.

**Closed by cris-oddball** 2024-08-15 20:24 UTC
Labels: Notify, Stretch, QA, Dev Reviewed, PM Reviewed, QA Reviewed, Off-track
