### ISSUE TITLE
Spike: Create environment specific docker container repositories  

### ISSUE THREAD

**Issue by ffafara-tw** [department-of-veterans-affairs/notification-api#112] opened 2020-07-09 16:13 UTC
May mean incurring some data transfer.

We also need to come up with lifecycle policy for our docker images in ECR, so that we don't generate cost by storing a large number of old images.

Purge old docker images from ECR

**Comment by miabecker** [comment] 2020-12-21 17:47
duplicate of #163

**Closed** 2020-12-21 17:47 UTC
