### ISSUE TITLE
Regular Update for Dependencies

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1203] opened 2023-04-07 19:27 UTC
## User Story - Business Need
We wish to keep dependencies up to date so we do not need such massive overhauls of our system. This will be a recurring ticket that will be done every sprint. We will update all dependencies we are able to. Any conflicts will get a ticket. This is intended to be a day of work at most because this is intended to update with only non-breaking changes.

### User Story
**As** VA Notify
**I want** to keep our service up to date
**So that** we are secure and as free of bugs as possible

### Additional Info and Resources
- Relevant section of [README.md](https://github.com/department-of-veterans-affairs/notification-api#update-requirementstxt)

## Engineering Checklist
- [x] Update performed
- [x] Any conflicts removed and tickets created
- [x] Passes all tests locally
- [x] Passes userflows and QA Suite testing against Dev
- [x] Any major changes are investigated (compare existing to new version changes)
  - [ ] Any questionable version changes are removed and a ticket is created
- [x] Tickets created are added to the Epic for tracking purposes

## Acceptance Criteria
Repo dependencies are updated and we have no broken functionality. Tickets created for any updates we could, or should, not do.

## QA Considerations
- [x] Check to see if these updates cancel out any Twistlock issues
- [x] QA Regression tests pass after deploying this code.
- [x] Lambda project-perf-va-profile-opt-in-out-lambda test passes
- [x] Billing still works as expected.

**Comment by mjones-oddball** [comment] 2023-04-11 21:05
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1203?planning-poker) with Zenhub @cris-oddball @EvanParish @jakehova @justaskdavidb2 @k-macmillan @kalbfled @ldraney

**Comment by mjones-oddball** [comment] 2023-04-11 21:06
This ticket is intended to become a template (eventually) for a recurring maintenance ticket per sprint. Until we try it a few times we will manually copy/paste to create tickets.

**Comment by kalbfled** [comment] 2023-04-19 14:45
@k-macmillan During the Flask upgrade, we didn't upgrade SQLAlchemy beyond v1.4.47 because v2.0 was brand new.  It's now on v2.0.9.  Should I attempt to upgrade that too under this ticket?

**Comment by kalbfled** [comment] 2023-04-19 17:20
I created #1224 and #1225.

**Comment by cris-oddball** [comment] 2023-04-20 18:31
@cris-oddball - be sure to test [this](https://github.com/department-of-veterans-affairs/notification-api/issues/1086) and billing.

**Comment by cris-oddball** [comment] 2023-04-24 14:57
Code passes regression (69/70 tests pass, the failed test is a result of the retries since we receive 429s for rate limiting on the current QA phone numbers - we still do not have new numbers from the provider yet.
```
================================================================================ short test summary info ================================================================================
FAILED tests/test_v2_notifications_z_notification_id.py::test_get_notification_statuses - Failed: ID ef1f26d3-cd29-4fa3-ab31-ba952dcdf649 reporting created after 5 attempts.
======================================================================= 1 failed, 69 passed in 201.07s (0:03:21) ========================================================================
```

**Comment by cris-oddball** [comment] 2023-04-24 15:57
Lambda test passes. 

project-perf-va-profile-opt-in-out-lambda lambda - use Opt-In-Opt-Out Test. Id not set use this payload, get a bearer token. the QP `"integration_test": ""` does not need any string value besides an empty string.

```
{
  "headers": {
    "authorization": "Bearer <token>"
  },
  "queryStringParameters": {
    "integration_test": ""
  },
  "body": {
    "txAuditId": "b62ab2c0-c8b4-4e92-b7ca-cae2a4163ee8",
    "bios": [
      {
        "txAuditId": "b62ab2c0-c8b4-4e92-b7ca-cae2a4163ee8",
        "sourceDate": "2023-04-23T19:14:35.435Z",
        "communicationPermissionId": 47,
        "vaProfileId": 1531,
        "communicationChannelId": 1,
        "communicationItemId": 5,
        "communicationChannelName": "Text",
        "communicationItemCommonName": "Disability and pension deposit notifications",
        "allowed": true
      }
    ]
  }
}
```

Response from Lambda:
```
[DEBUG]	2023-04-24T15:53:46.154Z		Getting the database URI from SSM Parameter Store . . .
[DEBUG]	2023-04-24T15:53:46.498Z		. . . Retrieved the database URI from SSM Parameter Store.
[DEBUG]	2023-04-24T15:53:46.498Z		Making a request to ACM . . .
[DEBUG]	2023-04-24T15:53:46.764Z		. . . Finished the request to ACM.
[DEBUG]	2023-04-24T15:53:46.764Z		Getting the ALB private key from SSM Parameter Store . . .
[DEBUG]	2023-04-24T15:53:47.004Z		. . . Retrieved the ALB private key from SSM Parameter Store.
START RequestId: 523507f3-a2ba-4fff-8cd4-1518113bd6cb Version: $LATEST
[INFO]	2023-04-24T15:53:47.008Z	523507f3-a2ba-4fff-8cd4-1518113bd6cb	POST request received.
[DEBUG]	2023-04-24T15:53:47.008Z	523507f3-a2ba-4fff-8cd4-1518113bd6cb	POST event: {'headers': {'authorization': 'Bearer <redacted>'}, 'queryStringParameters': {'integration_test': ''}, 'body': {'txAuditId': 'b62ab2c0-c8b4-4e92-b7ca-cae2a4163ee8', 'bios': [{'txAuditId': 'b62ab2c0-c8b4-4e92-b7ca-cae2a4163ee8', 'sourceDate': '2023-04-23T19:14:35.435Z', 'communicationPermissionId': 47, 'vaProfileId': 1531, 'communicationChannelId': 1, 'communicationItemId': 5, 'communicationChannelName': 'Text', 'communicationItemCommonName': 'Disability and pension deposit notifications', 'allowed': True}]}}
[DEBUG]	2023-04-24T15:53:47.008Z	523507f3-a2ba-4fff-8cd4-1518113bd6cb	This request is an integration test.
[DEBUG]	2023-04-24T15:53:47.009Z	523507f3-a2ba-4fff-8cd4-1518113bd6cb	Connecting to the database . . .
[DEBUG]	2023-04-24T15:53:47.466Z	523507f3-a2ba-4fff-8cd4-1518113bd6cb	. . . Connected to the database.
[DEBUG]	2023-04-24T15:53:47.466Z	523507f3-a2ba-4fff-8cd4-1518113bd6cb	Executing the stored function . . .
[DEBUG]	2023-04-24T15:53:47.481Z	523507f3-a2ba-4fff-8cd4-1518113bd6cb	. . . Executed the stored function.
[DEBUG]	2023-04-24T15:53:47.481Z	523507f3-a2ba-4fff-8cd4-1518113bd6cb	PUT request body: {'dateTime': '2023-04-23T19:14:35.435Z', 'status': 'COMPLETED_SUCCESS'}
[INFO]	2023-04-24T15:53:47.786Z	523507f3-a2ba-4fff-8cd4-1518113bd6cb	VA Profile responded to the PUT request with HTTP status 200.
[INFO]	2023-04-24T15:53:47.787Z	523507f3-a2ba-4fff-8cd4-1518113bd6cb	POST response: {'statusCode': 200, 'headers': {'Content-Type': 'application/json'}, 'body': '{"put_body": {"dateTime": "2023-04-23T19:14:35.435Z", "status": "COMPLETED_SUCCESS"}}'}
END RequestId: 523507f3-a2ba-4fff-8cd4-1518113bd6cb
REPORT RequestId: 523507f3-a2ba-4fff-8cd4-1518113bd6cb	Duration: 780.18 ms	Billed Duration: 781 ms	Memory Size: 128 MB	Max Memory Used: 95 MB	Init Duration: 1339.34 ms	

```

**Comment by cris-oddball** [comment] 2023-04-25 14:36
Billing validated - closing ticket.

**Closed by cris-oddball** 2023-04-25 14:36 UTC
Labels: Notify, QA, Dev Reviewed, PM Reviewed, Initial Review Passed, QA Reviewed
