### ISSUE TITLE
Upgrade VAProfileClient to use v3 API endpoints

### ISSUE THREAD

**Issue by AdamKing0126** [department-of-veterans-affairs/notification-api#1896] opened 2024-07-30 16:43 UTC
## User Story - Business Need

This ticket is to track IIR work on the VANotify board. It is not pointed since they have a ticket on their team's board for their efforts. Tracking ticket only.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

As a software developer working on the notifications-api repository
I want to update the code to the most recent API version
So that I can take advantage of the newest functionality

### Additional Info and Resources

[Related IIR Issue](https://github.com/department-of-veterans-affairs/va-iir/issues/891)

## Acceptance Criteria

When `VA_PROFILE_V3_USE_PROFILE_API_V3` feature flag is activated, requests to get a user's email address, phone number, or contact permissions will hit the `ProfileServiceV3#/Profile-v3/getProfile` endpoint

## QA Considerations
None - feature flag is not enabled in any environment higher than Perf

**Comment by cris-oddball** [comment] 2024-07-31 17:13
This is in an open PR and is being reviewed. Feature Flag is only enabled for dev, so there will be no testing in Perf.

**Comment by cris-oddball** [comment] 2024-08-01 17:00
Still in review, with changes requested.

**Comment by cris-oddball** [comment] 2024-08-02 16:52
Code is approved/merged, will send up in Pipeline to Perf and hold there until Monday (no deploys on Friday)

**Comment by cris-oddball** [comment] 2024-08-02 18:20
This has failed the regression on Perf due to the communication items preferences, in which these types of notification are stuck in Created.  More details to follow as I look into the specifics of the test failures. This feature flag is not enabled in Perf but the code to handle this requirement has been modified.

@kalbfled has agreed to revert the changes.

@AdamKing0126 can you please take a look with one of our devs? Thanks. 

cc/ @k-macmillan

**Comment by cris-oddball** [comment] 2024-08-05 14:56
The regression on Friday failed due to the request to vaprofile timed out and the exception was not caught or handled correctly, spraying the logs with a traceback and not retrying the request. @kalbfled to pair with @AdamKing0126 today to finish up this PR.

Blocks #1800

**Comment by cris-oddball** [comment] 2024-08-06 17:54
PR is approved and merged, deploying up through the food chain.

**Closed** 2024-08-06 18:40 UTC
Labels: Notify
