### ISSUE TITLE
Explicit Logic - Implement Logic for Communication Items

### ISSUE THREAD

**Issue by EvanParish** [department-of-veterans-affairs/notification-api#1227] opened 2023-04-19 18:41 UTC
### User Story(ies)
**As** the VA Notify platform
**I want** the ability to check the default sending logic for communication items
**So that** we can make sure a notification is only sent to a veteran if the permissions are set correctly for the communication item.

### Additional Info and Resources
- This is a follow-up to the Explicit Preferences spike that generated this [document](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/explicit_preference_logic.md). It explains the current permissions flow and should be updated during the completion of this ticket.
---
- [x] Discuss with QA after picking up the ticket, since this requires much work up front for QA to be able to validate sending to recipients who have their communication items set one way or another.

## Engineering Checklist
_**Required**_

- [x] Update the logic in the `recipient_has_given_permission` method to check the new field in the communication item for the default value to return when a `CommunicationItemNotFoundException` is thrown
    - the exception means the veteran has not set their permissions for the given item
    - look in file: `app/celery/lookup_recipient_communication_permissions_task.py`
    - [x] If default_send_indicator = false and `CommunicationItemNotFoundException` is thrown, the notification **should not be sent**
    - [x] If default_send_indicator = false and `CommunicationItemNotFoundException` is thrown, the status should be "preference-declined" and the status_reason should be "No recipient opt-in found for explicit preference"
    - [x] If default_send_indicator = true and `CommunicationItemNotFoundException` is thrown, the notification **should be sent**
- [x] Update / Add Unit tests

## Acceptance Criteria
_**Required**_

![image.png](https://images.zenhubusercontent.com/62041308731c2b2cdc47288b/1e3c8ae4-0cb1-46f0-9123-2af1be8951c1)

**Explicit Scenarios (New):**

Given a communication item is assigned to a template in VA Notify, which has a default_send_indicator set to false
When you send an email or sms notification for that template using a recipient_identifier
And the recipient's selection in VA Profile for this communication_item_id is allowed = true
Then the notification should be sent to the recipient successfully

Given a communication item is assigned to a template in VA Notify, which has a default_send_indicator set to false
When you send an email or sms notification for that template using a recipient_identifier
And the recipient has no selection for this communication_item_id in VA Profile and a `CommunicationItemNotFoundException` is thrown
Then the notification should not be sent and the status is set to "preference-declined" with a status reason of "No recipient opt-in found for explicit preference"

Given a communication item is assigned to a template in VA Notify, which has a default_send_indicator set to false
When you send an email or sms notification for that template using a recipient_identifier
And the recipient's selection in VA Profile for this communication_item_id is allowed = true
Then the notification should not be sent and the status is set to "preference-declined"

**Default/Implicit Scenarios (Existing):**

Given a communication item is assigned to a template in VA Notify, which has a default_send_indicator set to true
When you send an email or sms notification for that template using a recipient_identifier
And the recipient's selection in VA Profile for this communication_item_id is allowed = true
Then the notification should be sent to the recipient successfully

Given a communication item is assigned to a template in VA Notify, which has a default_send_indicator set to true
When you send an email or sms notification for that template using a recipient_identifier
And the recipient has no selection for this communication_item_id in VA Profile and a `CommunicationItemNotFoundException` is thrown
Then the notification should be sent to the recipient successfully

Given a communication item is assigned to a template in VA Notify, which has a default_send_indicator set to true
When you send an email or sms notification for that template using a recipient_identifier
And the recipient's selection in VA Profile for this communication_item_id is allowed = true
Then the notification should not be sent and the status is set to "preference-declined"

## QA Considerations
This will require coordination with VAProfile to set communication items on the test users in dev, perf and staging so that this can be validated. Then automated tests will need to validate that the message is sent or not based on the user defaults. Full testing strategy to be added here after the initial conversation with the dev working this ticket.

Update: 
Testing will be manual in dev, perf, staging
- in dev/perf/staging (SQA) create a new template in the QA service that has default_send_indicator set to False (all the others are set to True by default)
- in dev (int), perf/staging (SQA), choose the secondary QA Suite user, who has no communication item set, use Postman to exercise the above scenarios, changing to the new template as needed
- modify the the secondary QA Suite user, to add the comm item as allowed = true; re-test.
- modify the secondary QA Suite user, to add the comm item as allowed = false; re-test.
A new ticket will be created to automate the above.

## Potential Dependencies
_Leave blank if n/a_
- DB ticket #1252 is done.

## Out of Scope
_Leave blank if n/a_

**Comment by mjones-oddball** [comment] 2023-05-12 12:59
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1227?planning-poker) with Zenhub @cris-oddball @EvanParish @jakehova @justaskdavidb2 @k-macmillan @kalbfled @ldraney

**Comment by tabinda-syed** [comment] 2023-05-15 15:30
Team Expectation: Please be in close communication with Cris throughout working on this ticket if you're the one who picks it up.

**Comment by cris-oddball** [comment] 2023-06-02 14:17
[QA Test Case Plan Document ](https://docs.google.com/document/d/1ZqvQoS6ZlKXJWI_POliLVJLy4IUTIsaJHCoLSz-upCg/edit?usp=sharing)(note that in the description, the last scenario in Explicit and the last scenario in Implicit are incorrect. The screenshot of the table is correct and the document is based on that table.

**Comment by mjones-oddball** [comment] 2023-06-02 16:30
@EvanParish when you're working on this can you please confirm whether the existing logic/code supports lookups for both email and sms? I suppose I made an assumption that it already worked that way but want to be 100% sure. @cris-oddball

**Comment by mjones-oddball** [comment] 2023-06-02 17:01
@EvanParish Sorry one more special request! Does our logic in the preference look up (today) pass along a channel indicator so that we are only looking up SMS responses if it's for an SMS template and email for email templates? Let me know if that doesn't make sense. I'm pondering about what is already coded today vs what was working purely based on how we were using it at time (e.g. until now preferences only had 1 channel associated, but it's possible for them to have 2 channels associated (email and sms) with different responses). It may not impact this ticket, but it will impact future work.

**Comment by EvanParish** [comment] 2023-06-02 19:29
@mjones-oddball It looks like it does. It took me a little bit to figure out what you were asking, but I get it now. When we are checking to see if communication is allowed we check the `communicationChannelName` against the notification type (email or sms) before checking if communication is allowed.

**Comment by cris-oddball** [comment] 2023-06-02 20:45
Test Plan is finalized (see linked doc above) I need to do the following:

- Set communication preferences on the 6 users using the VAProfile Communication API
- Set true/false on the communication items via our API (dev/perf at least, staging we have to be set them the way they are expected to be set)
- Set the communication_item_id on each of the templates I have configured in the 3 lower envs

I should be able to do that Monday morning.

**Comment by cris-oddball** [comment] 2023-06-02 21:13
@mjones-oddball @EvanParish just want to make sure I'm following along... to look up the va_profile_item_id in their system, our app makes a call to their API  '/communication-hub/communication-items/{id}'

and then we have to look at the following keys:
['bio']['communicationItemChannels'] which is an array of channels (ways to send a message).
Loop over the list to find key ['communicationChannel']['communicationChannelId'] where the value 1 indicates SMS and the value 2 indicates Email. There is another property, ['name'] whose values can be either 'Text' or 'Email'.

There is also a property under ['communicationItemsChannel'] called ['defaultSendIndicator'] - it is possible that this can get out of sync with our 'default_send_indicator' - we might want to keep that in mind somehow or at least configure our existing communication items to comply with that field -- which because of where it is nested in their list, can be configured one way for Email and another way for SMS, which our system doesn't consider.

Truncated object:
```
{
   'bio':  {
        'communicationItemsChannel': [
            {
                 'defaultSendIndicator': true,
                 'communicationChannelId': 1
                 'name': 'Text'
            }
        ]
    }
}
```

**Comment by cris-oddball** [comment] 2023-06-05 16:09
Regarding testing, I was hoping to have two different templates per channel for testing (4 templates), but the only communication item that we have in our databases for email is the Covid-19 item. There are 5 other communication items available in VAProfile that can be used for email, however we don't have them in our system.

- Email Default Send True - can be set to use communication-item-id 2 for "COVID-19 Updates"
- Email Default Send False - cannot be set, no other email communication-item-id available in our DB
- SMS Default Send True - can be set to use communication-item-id 1 for "Board of Veterans' Appeals hearing reminder"
- SMS Default Send False - can be set to use communication-item-id 5 for "Comp and Pen Payment Notifications"

This will not work for automation. For manual testing, we can flip the Covid-19 item to "default_send_indicator": false and just re-use the Email Default Send True template.

**Comment by cris-oddball** [comment] 2023-06-06 22:35
Evan updated the communication-items in the databases (info in the test plan doc, linked above), DEV users updated with send preferences.

Perf templates updated with the correct communication-items.

I need to configure the Perf users' end preferences via the VAProfile endpoints, then will be ready to validate. Will need to draft a ticket for automation but will do that when the code is on Perf.

**Comment by cris-oddball** [comment] 2023-06-09 22:01
**QA TESTING PERF**

User’s VA Profile ID 120451 has no selection for any communication items

- [ ] TC01 EMAIL: template “Email Default Send True”; expect a successful send and CommunicationItemNotFoundException is seen in logs.
- [ ] TC02 EMAIL: template “Email Default Send False”; expect an unsuccessful send, the status is set to "preference-declined" with status "No recipient opt-in found for explicit preference", and CommunicationItemNotFoundException is seen in logs.
- [ ] TC03 SMS: template “SMS Default Send True”; expect a successful send and CommunicationItemNotFoundException is seen in logs.
- [ ] TC04 SMS: template “SMS Default Send False”; expect an unsuccessful send, the status is set to "preference-declined" with status "No recipient opt-in found for explicit preference", and CommunicationItemNotFoundException is seen in logs.

User’s VA Profile 1273722 has the above communication items set to “allowed”: “true”

- [ ] TC05 EMAIL: template “Email Default Send True”; expect a successful send.
- [ ] TC06 EMAIL: template “Email Default Send False”; expect a successful send.
- [ ] TC07 SMS: template “SMS Default Send True”; expect a successful send.
- [ ] TC08 SMS: template “SMS Default Send False”; expect a successful send.

User’s VA Profile 1273724 has the has the above communication items set to “allowed”: “false”

- [ ] TC09 EMAIL: template “Email Default Send True”; expect an unsuccessful send, with status preference-declined.
- [ ] TC11 EMAIL: template “Email Default Send False”; expect an unsuccessful send, with status preference-declined.
- [ ] TC10 SMS: template “SMS Default Send True”; expect an unsuccessful send, with status preference-declined.
- [ ] TC12 SMS: template “SMS Default Send False”; expect an unsuccessful send, with status preference-declined.

**Comment by cris-oddball** [comment] 2023-06-09 23:07
**QA PASSES**

- [ ] Test cases above all pass in that the expected outcome is found in each case
- [ ] Regression passes

Holding ticket until Monday to ask about the `CommunicationItemNotFoundException` not being seen in the logs.

**Comment by cris-oddball** [comment] 2023-06-12 14:10
Evan confirmed that `CommunicationItemNotFoundException` will not be seen in the logs, closing ticket.

**Closed by cris-oddball** 2023-06-12 14:10 UTC
Labels: Notify, QA, Dev Reviewed, PM Reviewed, QA Reviewed, Off-track
