### ISSUE TITLE
Remove Endpoints - letter and pdf

### ISSUE THREAD

**Issue by EvanParish** [department-of-veterans-affairs/notification-api#1178] opened 2023-03-21 20:48 UTC
## User Story - Business Need

In the effort to clean up our code we need to investigate and remove unused endpoints. This ticket is to take a look at the endpoints under `/v2/notifications/<notification_id>/pdf` and remove the ones marked for removal. You can view the table of endpoints [here](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/VA%20Notify%20Endpoints.md).

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)
**As an** engineer
**I want** to clean up and reduce our codebase
**So that** it is easier to maintain and upgrade in the future.

### Additional Info and Resources
- [Endpoint Table](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/VA%20Notify%20Endpoints.md)
- [Endpoint Spreadsheet](https://docs.google.com/spreadsheets/d/18AfqlEOWlrnigauO57jA0VP3RMHTaP4luknqBxrcbuY/edit#gid=115873237)
- [How To Guide for similar code clean up for 1149](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Process/Coding/UnusedCodeRemoval.md)

Be sure to look for things not explicitly called out in this ticket, such as the 'postage' field in notifications and [this method ](https://github.com/department-of-veterans-affairs/notification-api/blob/3d1ab99e22fd78efdfa72ca3e43ebab7c8cb0000/app/service/send_notification.py#L135) send_pdf_letter_notification(service_id, post_data). There may be lots of details scattered throughout and these should be removed when the routes are removed.  There are also S3 buckets that apparently store letters - determine what to do with them as well (cost reduction).

## Engineering Checklist

- [x] Investigate the endpoints starting with `/v2/notifications/<notification_id>/pdf` to make sure they aren't being used
- [x] Also take a look at and remove this endpoint `/v2/notifications/letter`
- [x] Remove tests associate with those endpoints
- [x] Remove letters_pdf_tasks & test_letters_pdf_tasks
- [x] Remove the code associated with those endpoints (if possible). Make sure not to remove any code used by other parts of the application.
- [x] Note that some of this in in Utils. pypdf is used in Utils only for `/v2/notifications/<notification_id>/pdf` - double-check and create a ticket to remove that code and those tests that use pypdf or any functionality related to these routes.

## Acceptance Criteria

- When the designated code and tests have been removed, the application retains full functionality. 

## QA Considerations
- [ ] The QA Regression Suite passes
- [ ] The Cypress regression passes

## Potential Dependencies
- Make sure the removal of these endpoints doesn't affect the work Strike is doing.

**Comment by mjones-oddball** [comment] 2023-03-29 16:11
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1178?planning-poker) with Zenhub @cris-oddball @EvanParish @jakehova @justaskdavidb2 @k-macmillan @kalbfled @ldraney

**Comment by kalbfled** [comment] 2023-09-29 19:35
@k-macmillan @mjones-oddball After this ticket is merged, we can have a new ticket to remove the remaining letter functionality, including dao code and fixtures.  This is a more complicated task because it involves changing database models.  For example, a Notification has attributes like "postage".  Things that need to change can be found by running `grep -rni letter` from the repo root directory.

**Comment by cris-oddball** [comment] 2023-10-03 19:52
Modified PR that is tighter in scope was approved and merged, tagged and sent up to Perf. Awaiting regression results.

**Comment by cris-oddball** [comment] 2023-10-03 20:49
hrm.... results of regression:
```
FAILED tests/test_v2_notifications_email.py::test_get_email_notification_statuses
============= 1 failed, 189 passed, 3 xfailed in 178.23s (0:02:58) =============
Error: Process completed with exit code 1.
```

with the failure as
```
 >           raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
E           requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Because the response was
```
self = <json.decoder.JSONDecoder object at 0x7f8d3a6bbee0>
s = '<html><head><title>Request Rejected</title></head><body>The requested URL was rejected.  <br><br>\r\n\r\nThe enhanced...upport ID number.\r\n\r\n<br><br>Your support ID is: 15121636945514988209<br>Appliance name: gwslb01-waf</body></html>'
idx = 0
```

???
Checking logs and then
Running a local regression just to email smoke tests (since the above regression is against the public endpoints)

**Comment by cris-oddball** [comment] 2023-10-03 21:08
Passed in the [cloud against Perf](https://github.com/department-of-veterans-affairs/notification-api-qa/actions/runs/6398331884).

Passed locally against Perf
```
 190 passed, 3 xfailed in 204.51s (0:03:24)
```

Re-running just the regression part of that action that failed.

**Comment by cris-oddball** [comment] 2023-10-03 21:18
Re-running the regression, but this time using the [Deploy to Env action](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/6398518549) with the env set to Perf.

**Comment by cris-oddball** [comment] 2023-10-03 21:57
This time, the regression against the public endpoints via the cloud passed.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdGYvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8f4a2ee8337c5e842e43b2f6a9e4e92b27aad2f0/Screen%20Shot%202023-10-03%20at%203.56.52%20PM.jpg)

Closing ticket.

**Closed by cris-oddball** 2023-10-03 21:57 UTC
Labels: Tech Debt, Notify, QA, Off-track
