### ISSUE TITLE
IIR - Update VAPRO Contact Lookup to Filter by Valid Phone Numbers

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#2009] opened 2024-09-24 13:59 UTC
## User Story - Business Need
Currently, VA Notify attempts to deliver SMS to any mobile phone number found in VA Profile. Sometimes these SMS fail because the "mobile" phone recorded in VA Profile is actually a landline or other invalid type for texting. Rather than attempting to text a number that will not succeed, we should use the phone validation data provided by VAPRO to determine if it makes sense to proceed to delivery, or fail and alert the client (via callbacks) that the phone number was invalid - thus making the person unreachable by SMS.

See [IIR-900](https://github.com/department-of-veterans-affairs/va-iir/issues/900)

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** Business  
**I want** to know if the Veteran is unreachable by SMS due to an invalid phone number
**So that** I can ensure they are receiving the information I'm sending them, and determine if alternate communications are required

**As** VA Notify  
**I want** to determine if a phone number is valid before proceeding to delivery
**So that** I can efficiently process notifications, and deliver status information back to businesses ASAP if a recipient is unreachable

### Additional Info and Resources

- [Parent spike 792 with details in the comments](https://app.zenhub.com/workspaces/va-iir-6508c0bd79e64e0fb5855caf/issues/gh/department-of-veterans-affairs/va-iir/792)
- [Profile API Notes](https://docs.google.com/document/d/1rH2Q9ijrI41EOGGZfjaWP3To5AvbttmqMGSdz6JbW94/edit#heading=h.pe5qko4ekebd)
- Metadata about phone numbers may be available from the Profile API, which would allow us to confirm that a number is a cell phone. This lives in the response to a Contact Information request under telephones, then in the TelephoneResponse object we're interested in classification then classificationCode.
- Classifications:
```
{
  "classificationList": [
    {
      "classificationCode": 0,
      "classificationName": "MOBILE"
    },
    {
      "classificationCode": 1,
      "classificationName": "LANDLINE"
    },
    {
      "classificationCode": 2,
      "classificationName": "VOIP"
    },
    {
      "classificationCode": 3,
      "classificationName": "INVALID"
    },
    {
      "classificationCode": 4,
      "classificationName": "OTHER"
    },
    {
      "classificationCode": 5,
      "classificationName": "PREPAID"
    }
  ]
}
```

## Acceptance Criteria

- [x] Valid phone number proceeds with delivery

> GIVEN VA Profile returns a mobile phone number
> WHEN the classification is mobile (0), voip (2), prepaid (5)
> OR a classification is not provided
> THEN proceed to SMS delivery

- [ ] Invalid phone number fails prior to delivery and status is sent to client via callback if applicable

> GIVEN VA Profile returns a mobile phone number
> WHEN the classification is landline (1), invalid (3), or other (4)
> THEN raise a `VAProfileNonRetryableException` with status: `permanent-failure` and status_reason: `Phone number is invalid`

**Comment by mjones-oddball** [comment] 2024-09-24 14:17
Noting that we determined other was not a valid type because of AWS's reply:
Occasionally, the response from the phone number validation service includes a PhoneType value of OTHER. The service might return this kind of response in the following situations:

- The phone number is a toll-free (freephone) number.
- The phone number is reserved for use in TV shows and movies, such as North American phone numbers that begin with 555.
- The phone number includes an area code that is not currently in use, such as the 999 area code in North America.
- The phone number is reserved for some other purpose.

VA Profile said there were currently 32,379 flagged as OTHER as of 9/3.

Other breakdowns below:
<img width="1418" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMS82Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3177b1a4c5cdfd0296372d4aeeccc0e10f9bb5be/image.png" alt="image.png" />

**Comment by cris-oddball** [comment] 2024-09-24 16:43
@EvanParish and @AdamKing0126 to sync on this before the branch is deployed, then Evan will sync with me for testing notes.

**Comment by cris-oddball** [comment] 2024-09-25 16:26
Evan touched base with me about testing. We discussed:

- setting the feature flag to False in Perf, Staging, Prod, that way I can turn it on in Perf when able to test and can ensure that with the test flag as false, everything works as expected
- adding a task definition file for prod now
- adding celery task definitions.

**Comment by cris-oddball** [comment] 2024-09-27 20:03
PR is approved and merged. Sending this to Perf and holding it there until Monday.

**Comment by cris-oddball** [comment] 2024-09-27 21:09
On Perf, with Flag disabled, I have verified that Pinpoint is still handling Phone Validation failures by changing a test user's contact Mobile to a prefix 555 number and observing in the logs a Pinpoint `event_type=_SMS.FAILURE` and observing the test logs for the feature:
> V3 Profile -- VA_PROFILE_V3_IDENTIFY_MOBILE_TELEPHONE_NUMBERS is not enabled.  Will not check classification info.

Will deploy this up to Prod (staging and prod feature flags are off), then cut a branch to flip Perf on and test that the feature flag works as expected.

**Comment by cris-oddball** [comment] 2024-09-30 14:02
This was sent up to Staging/Prod. 
Will find time to cut a branch to turn the FF on in Perf and test, but this ticket may carry until tomorrow.

**Comment by cris-oddball** [comment] 2024-09-30 15:41
Deployed branch out to Perf with the Feature Flag enabled for telephone numbers.

When the regression ran, found the following logs showing that the new feature is in use for all sms records sent:
<img width="1685" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU1QQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5e4ac844b62d405fde1e300f47fc57881a01c74d/Screenshot%202024-09-30%20at%209.41.02%E2%80%AFAM.jpg" alt="Screenshot 2024-09-30 at 9.41.02 AM.jpg" />



Can begin testing the feature now.

**Comment by cris-oddball** [comment] 2024-09-30 16:05
**QA TESTING IN PROGRESS**

**Happy Path**
Expect status: delivered
- [ ]  Valid phone number proceeds with delivery for a mobile number - Using my own mobile
- [ ]  Valid phone number proceeds with delivery for a VOIP number "[+18042221111](https://testcall.com/804-222-1111/)"
- [ ]  Valid phone number proceeds with delivery for a Prepaid number (unable to test as do not have a prepaid number available

**Negative Test Cases**
Expect status: permanent-failure and status_reason: Phone number is invalid

- [ ]  Invalid phone number fails prior to delivery and status is sent to client via callback if applicable for landline
- [ ]  Invalid phone number fails prior to delivery and status is sent to client via callback if applicable for an invalid number
- [ ]  Invalid phone number fails prior to delivery and status is sent to client via callback if applicable for Other

**Comment by cris-oddball** [comment] 2024-10-03 14:07
The fix for the above failures is being sent up to Prod right now. Feature Flag is off in Perf, Staging, Prod. 

When I have time, I will set the FF to True in Perf and retest. Might be today (Thurs) or tomorrow (Fri).

**Comment by cris-oddball** [comment] 2024-10-03 22:40
**QA TEST IN PROGRESS**

Enabled FF in Perf on a branch

**Happy Path**
Expect status: delivered
- [ ]  Valid phone number proceeds with delivery for a mobile number - Using my own mobile
- [ ]  Valid phone number proceeds with delivery for a VOIP number "[+18042221111](https://testcall.com/804-222-1111/)"
- [ ]  ~Valid phone number proceeds with delivery for a Prepaid number~ 
- unable to test as do not have a prepaid number available

**Negative Test Cases**
- expect the phone to be validated by VAPRO and not the SMS sender.
- expect a callback with the correct info sent if callback is on the service
- expect for failures: `'status': 'permanent-failure'` and `'status_reason': 'Phone number is invalid'`
<br></br>
- [ ]  Invalid phone number fails prior to delivery and status is sent to client via callback if applicable for landline - Using test landline  "[+16317918378](http://thetestcall.blogspot.com/)"
- 
<br></br>
- [ ]  Invalid phone number fails prior to delivery and status is sent to client via callback if applicable for  other/invalid number (number used in the US for television) "17195551212"
- 
<br></br>
- [ ]  Invalid phone number fails prior to delivery and status is sent to client via callback if applicable for other/invalid tollfree "+18002211212" (Delta Airlines)
- 
<br></br>
- [ ]  ~Invalid phone number fails prior to delivery and status is sent to client via callback if applicable for other/invalid tollfree "+19991234567" (999 is not a valid area code)~ 
- Unable to validate because the app itself will not allow a veteran to change their number to a non-valid US area code.

**Comment by cris-oddball** [comment] 2024-10-03 23:39
Closing this ticket as Done, noting that before the next set of tickets can be worked (which remove the feature flags) we probably want to enable the feature flags for both features all the way up to Prod.

@EvanParish @k-macmillan

**Closed by cris-oddball** 2024-10-03 23:39 UTC
Labels: Notify, QA
