### ISSUE TITLE
BUG: result_status not set when a Veteran has opted out

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#826] opened 2022-09-08 19:41 UTC
## Description
Notifications do not show a `result_status` when a recipient has opted out. We receive `_SMS.FAILURE` for opt outs, but we were only checking for `_SMS.OPTOUT`. We may need to look for additional information to determine if it was an opt out.

## Expected behavior

- [ ] A descriptive status is shown.
- [ ] Evaluate and add missing tests related to this

## Additional Information
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/f03f2ead-7661-419e-9066-f57f744d9d5f)

We attempt to map the record status here:
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/7e79e666-1ceb-4e89-b5cc-fe5f6e9bb135)

But it never should have made it there because the method that calls that one should have found it was an opt-out:
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/837f1ed8-74b9-4eef-8b40-608828ecda69)

The method that checks it:
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/c87fe1dc-71ad-4156-9be4-888b221b7f61)

And the value received in AWS:
>received callback from Pinpoint with event_type of _SMS.FAILURE and record_status of Failed to send because +1[redacted] is opted out

**Comment by mjones-oddball** [comment] 2022-10-05 13:58
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/826?planning-poker) with Zenhub @cris-oddball @EvanParish @ianperera @jessecanderson @k-macmillan @kalbfled @trevor2718 @jakehova

**Comment by mjones-oddball** [comment] 2022-10-05 15:59
Cris will pair up with whatever engineer takes this to tackle the test topic

**Comment by mjones-oddball** [comment] 2023-08-29 21:31
Duplicate of #1434

**Closed by mjones-oddball** 2023-08-29 21:31 UTC
Labels: bug, Notify, QA
