### ISSUE TITLE
Two Way Message Enhancement: Support for All Clients

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#1535] opened 2023-11-09 17:36 UTC
## User Story - Business Need

As we onboard clients interested in two way messaging with SMS, we need a repeatable process rather than requiring duplicative infra or engineering effort per client. Currently, this feature is hardcoded to only accept VEText's endpoint credentials which limits us when setting up other clients.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** business line
**I want** to establish two way SMS communication with Veterans
**So that** Veterans can reply to take an action via text message (e.g. cancel appt, confirm appt, etc.)

### Additional Info and Resources

- https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/SMS-Inbound.md

### Changes Needed
- [x] Create a new field named `auth_parameter` in the inbound numbers table to capture the parameter name. This is needed so we can look up the credentials for the auth header when sending replies to the client endpoint.
- [x] Update execution environment setup to pull all those values and update the `two_way_sms_table_dict` dictionary for that service
- [x] Update header code to check this new field rather than using the hardcoded parameter name for VEText (see image below)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWkvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--60cdce6c1068593ee1af8b5481b1a191508dd563/image.png)

- [x] Update `inbound-number` routes in Postman:
    - [x] The update route is missing from the postman collection, but exists in the code, please add that
    - [x] Add the new field `auth_parameter` to the create, update, and get routes
- [x] Update swagger openapi doc, https://github.com/department-of-veterans-affairs/notification-api/blob/master/documents/openapi/openapi.yaml
- [x] Update configuration section of [documentation](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/SMS-Inbound.md) to include
  - [x] HOW to add the params, in this file `cd/application-infrastructure/two_way_forwarding_auth.tf` in Infra
  - [x] Please note, if a client (service) has more than 1 set of credentials please include use case in the parameter naming. e.g. "...-bva-hearing-reminders
  - [x] The information in this ticket

### Updates and Testing in Staging
- [x] VEText: update the new staging vetext two way parameter for `vetext-1` using the existing value from `/staging/notification-api/vetext/vetext_api_token`
- [x] VEText: update the inbound numbers containing url endpoints to add the new parameter name, see https://github.com/department-of-veterans-affairs/vanotify-infra/issues/686
- [x] VEText: Confirm these 2 inbound setups still work (this is for BVA Hearing and Prescription Shipment Notifications)
----

- [x] PeriOptimization: Talk to Kyle for auth info and add this to parameter store via the new infra https://github.com/department-of-veterans-affairs/vanotify-infra/issues/686
- [x] PeriOptimization: In AWS Pinpoint go to details for `+15075025215`:
    - [x] Enable 2 way via the checkbox
    - [x] Select the `staging-notify-incoming-sms` SNS topic
    - [x]  Check off "Enable self-managed opt outs" which disables stop mgmt in Amazon 
- [x] PeriOptimization: Add `+15075025215` as an inbound number with url endpoint `http://periop.perioptimization.com/vanotify/VANotifyResponse` and applicable parameter name
- [x] PeriOptimization: Update sms sender to `+15075025215` and add the inbound number id from the previous step
- [x]  PeriOptimization: Test the inbound setup
----
- [x] Query Staging inbound numbers table to confirm there's no other configurations we missed. Given it was hardcoded to VEText the likelihood is low. VA Insurance has 2 way set up, but it doesn't use the same process.

### Prep for deployment to Prod
We will need to ensure configurations get updated for VEText during the deployment, once the new inbound numbers field exists to not break live functionality. They will need to send a test text through for the 2 phone numbers to ensure you're seeing traffic successfully send to VEText in the logs.

- [x] Update the appropriate deployment ticket: https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/vanotify-team/1142  (Jan 10 deploy)

## Acceptance Criteria

GIVEN a sender phone number is enabled for inbound
WHEN you text "Hello" to the sender phone number
THEN you can see in the logs that the connection for the associated endpoint is successfully made to pass along the inbound message

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

Unless we have our own endpoint to test with, we may have to just test this in Staging with VEText's BVA hearing reminders (regression to confirm it still works) and the new 2 way setup for PeriOptimization.

## Out of Scope
_Leave blank if n/a_

We're not ready to set up 2 way in prod for PeriOptimization

**Comment by mjones-oddball** [comment] 2023-11-13 13:53
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1535?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by EvanParish** [comment] 2023-12-13 23:34
So testing this has proved to be much more difficult than originally anticipated. 
**Updates so far:**
- When setting up the perioptimization inbound number I thought the `service_id` field should be populated when I created or updated it, but after attempting to add the inbound number to the perioptimization sms-sender and digging through the code for a while, it looks like that field is supposed to be populated when the inbound number is added to a service's sms-sender.
  - I'm removing the `service_id` field from the update and delete routes in the OpenAPI docs and Postman for inbound-numbers as a result.
  - fixing this required getting into the database and to remove the `service_id` from the inbound number so I could add it to the proper sms-sender
- When testing the `project-staging-notify-incoming-sms-lambda` I attempted connections with various verification configurations to ensure we are using the correct setup that will get us connected to our clients

**Current Issues:**
- Currently the perioptimization connection is not working and causing the messages to be added to the retry queue
  - i attempted both using http and https connections with one timing out and the other refusing the connection. This seems to be a configuration issue on Perioptimization's side.

**Comment by EvanParish** [comment] 2023-12-14 22:13
I reached out to Rob Durkin to see ask about the two different urls for our inbound numbers. Is one outdated and should not be used? Or, is there some reason we have 2 different urls?
"https://staging.ng.vetext.va.gov/inbound" - works with `notify-incoming-sms-lambda`
vs
"https://staging.api.vetext.va.gov/api/vetext/pub/inbound-message/aws" - throws 403

I also reached out to our PeriOptimization point of contact ([shankara@switchlane.com](mailto:shankara@switchlane.com)) because we are running into an error with the connection being refused by perioptimization in staging. This seems to be a configuration issue on their end, so working with them should resolve the issue.

**Comment by EvanParish** [comment] 2023-12-15 13:23
Shankara reached out and said they fixed an SSL issue on their end. It looks like we can now connect to PeriOptimization!

Still no word on the vetext situation though. It looks like Rob is OOO right now.

**Comment by cris-oddball** [comment] 2023-12-15 15:45
updated description with link to the Jan 10 deploy, since this will not make the Dec 20 deployment.

**Comment by EvanParish** [comment] 2023-12-18 22:21
I did another test in staging today with master and then deployed and tested my branch again. I made sure the configuration was all correct. All endpoints worked during today's tests! 

vetext long url:
<img width="1662" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE51QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ae3770fad5d3698179cb5cc12cb5d20a391f88a/image.png" alt="image.png" />


vetext short url:
<img width="1666" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFJ1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4181bae524239922a01b85868fccb44ce00d7628/image.png" alt="image.png" />

perioptimization url:
<img width="1659" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFZ1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a071417674d8cc8ac065ae1138d0ef9ae619fab8/image.png" alt="image.png" />

**Comment by cris-oddball** [comment] 2023-12-19 22:24
PR approved and merged to master in Infra and API, tags cut and pushed to Perf for testing.

**Comment by cris-oddball** [comment] 2023-12-19 22:58
**PASSED** Ran regression with the QA branch that contains GET tests for the inbound-numbers routes on Perf.

<img width="927" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemwxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d2ab166979a2c9ca09e192d001da39f3958a1f54/Screenshot%202023-12-19%20at%203.57.26%E2%80%AFPM.jpg" alt="Screenshot 2023-12-19 at 3.57.26 PM.jpg" />


Manual testing for POST routes next, some of which will need to wait until tomorrow.

**Comment by cris-oddball** [comment] 2023-12-20 15:09
I wrote 22 test cases for these routes (and could have written more).  Will likely just open bug tickets if I run into any failures. Testing should take most of the morning, but then I'll have a plan for the automation.

**Comment by cris-oddball** [comment] 2023-12-20 18:33
**PASSED** - CREATE Happy Path POST Test Cases

- [ ]  TC01 - Create inbound-number with only required fields (number and provider), expect 201 and expected response
POST body
```
{
    "number": "+13035551212",
    "provider": "ExampleProvider",
}
```

EXPECTED RESPONSE
```
{
  "data": {
    "active": true,
    "auth_parameter": null,
    "id": <generated UUID>, # e80b7193-7a80-4f4a-861e-85e4d3172410
    "number": "+13035551212",
    "provider": "ExampleProvider",
    "self_managed": false,
    "service": null,
    "url_endpoint": null
  }
}
```

- [ ]  TC-02 - Create inbound-number with optional properties and self-managed as true (here, url is required), expect 201 and expected response
POST body
```
{
    "active": false,
    "auth_parameter": "some/parameter",
    "number": "+17195551212",
    "provider": "qatest",
    "self_managed": true,
    "url_endpoint": "http://example.com/api"
}
```

EXPECTED RESPONSE
```
{
  "data": {
    "active": false,
    "auth_parameter": "some/parameter",
    "id": <generated UUID>, # 72a2198d-64a3-4fbf-8cc7-ea01928c32e3
    "number": "+17195551212",
    "provider": "qatest",
    "self_managed": true,
    "service": null,
    "url_endpoint": "http://example.com/api"
  }
}
```

- [ ] TC03 - Create inbound-number with optional properties and self-managed as false (here, url is optional), expect 201 and expected response
POST body
```
{
    "active": false,
    "auth_parameter": "some/parameter",
    "number": "+12135551212",
    "provider": "qatest",
    "self_managed": false
}
```

EXPECTED RESPONSE
```
{
  "data": {
    "active": false,
    "auth_parameter": "some/parameter",
    "id": <generated UUID>, # de2f9116-f198-4a16-b7e3-149603ce452d
    "number": "+12135551212",
    "provider": "qatest",
    "self_managed": false,
    "service": null,
    "url_endpoint": null
  }
}
```

**Comment by cris-oddball** [comment] 2023-12-20 18:34
**PASSED** DEACTIVATE Happy Path POST Test Case

- [ ]  TC04 Run the route with the ID e80b7193-7a80-4f4a-861e-85e4d3172410 from TC01, expect 204 No Content & Use the GET route to validate that the active field is now set to false

**Comment by cris-oddball** [comment] 2023-12-20 18:35
**PASSED** UPDATE Happy Path POST Test Cases

-[ ] TC05 update the following parameters using the ID from TC01 `e80b7193-7a80-4f4a-861e-85e4d3172410`, expect 201 and the response to include the updated parameters
```
{
  "active": true, 
  "auth_parameter": "a/different/parameter",
  "number": "+14155551212",
  "provider": "qatest",
  "self_managed": true,
  "url_endpoint": "http://example.com/api"
}
```

EXPECTED RESPONSE
```
{
  "data": {
    "active": true,
    "auth_parameter": "a/different/parameter",
    "id": "e80b7193-7a80-4f4a-861e-85e4d3172410"
    "number": "+14155551212",
    "provider": "qatest",
    "self_managed": true,
    "service": null,
    "url_endpoint": "http://example.com/api"
  }
}
```

**Comment by cris-oddball** [comment] 2023-12-20 18:43
**CONDITIONAL PASS** Create Negative POST test cases
Found existing bugs in this route, outside the scope of the work performed in this ticket. Opening a bug ticket and including it in a comment on this ticket prior to closing ticket.

- [ ]  TC06 Create inbound-number with self-managed as true (here, url is required) but without a url_endpoint, expect 400 and a response indicating failure and reason
```
{
  "active": false,
  "auth_parameter": "some/parameter",
  "number": "+12055551212",
  "provider": "qatest",
  "self_managed": true
}
```

ACTUAL RESPONSE:
```
{
    "errors": [
        {
            "error": "ValidationError",
            "message": "url_endpoint is a required property"
        }
    ],
    "status_code": 400
}
```

- [ ]  TC07 Create inbound-number with self-managed as string, not bool, expect 400 and a response indicating failure and reason
```
{
  "active": false,
  "number": "+12055551212",
  "provider": "qatest",
  "self_managed": "string"
}
```

ACTUAL RESPONSE:
```
{
    "errors": [
        {
            "error": "ValidationError",
            "message": "self_managed string is not of type boolean"
        }
    ],
    "status_code": 400
}
```

- [ ] TC08 Create inbound-number with active as string, not bool, expect 400 and a response indicating failure and reason
```
{
  "active": "string",
  "number": "+12055551212",
  "provider": "qatest"
}
```

ACTUAL RESPONSE:
```
{
    "errors": [
        {
            "error": "ValidationError",
            "message": "active string is not of type boolean"
        }
    ],
    "status_code": 400
}
```

- [ ] TC09 Create inbound-number with auth_parameter as bool, not string, expect 400 and a response indicating failure and reason
```
{
  "active": false,
  "number": "+12055551212",
  "provider": "qatest",
  "auth_parameter": true
}
```

ACTUAL RESPONSE:
```
{
    "errors": [
        {
            "error": "ValidationError",
            "message": "auth_parameter True is not of type string"
        }
    ],
    "status_code": 400
}
```

- [ ] TC10 Create inbound-number with number as bool, not string, expect 400 and a response indicating failure and reason
```
{
  "active": false,
  "number": true,
  "provider": "qatest"
}
```

ACTUAL RESPONSE:
```
{
    "errors": [
        {
            "error": "ValidationError",
            "message": "number True is not of type string"
        }
    ],
    "status_code": 400
}
```

- [ ] TC11 Create inbound-number with provider as bool, not string, expect 400 and a response indicating failure and reason
```
{
  "active": false,
  "number": "+12055551212",
  "provider": true
}
```

ACTUAL RESPONSE:
```
{
    "errors": [
        {
            "error": "ValidationError",
            "message": "provider True is not of type string"
        }
    ],
    "status_code": 400
}
```


- [ ] TC12 Create inbound-number with url_endpoint as bool, expect 400 and a response indicating failure and reason
```
{
  "active": false,
  "number": "+12055551212",
  "provider": "qatest",
  "url_endpoint": true
}
```

ACTUAL RESPONSE:
```
{
    "errors": [
        {
            "error": "ValidationError",
            "message": "url_endpoint True is not of type string"
        }
    ],
    "status_code": 400
}
```

- [ ] TC13 Create inbound-number with number but without provider, expect 400 and a response indicating failure and reason
```
{
  "active": false,
  "number": "+12055551212"
}
```

ACTUAL RESPONSE:
```
{
    "errors": [
        {
            "error": "ValidationError",
            "message": "provider is a required property"
        }
    ],
    "status_code": 400
}
```

- [ ] TC14 Create inbound-number with provider but without number, expect 400 and a response indicating failure and reason
```
{
  "active": false,
  "provider": "qatest"
}
```

ACTUAL RESPONSE:
```
{
    "errors": [
        {
            "error": "ValidationError",
            "message": "number is a required property"
        }
    ],
    "status_code": 400
}
```

- [ ] TC15 Create inbound-number with non-unique number, expect 400 and a response indicating failure and reason
**BUG** 
```
{
    "active": false,
    "auth_parameter": "some/parameter",
    "number": "+14155551212",
    "provider": "qatest",
    "self_managed": true,
    "url_endpoint": "http://example.com/api"
}
```

ACTUAL RESPONSE:
500 
```
{
    "message": "Internal server error",
    "result": "error"
}
```

**Comment by cris-oddball** [comment] 2023-12-20 18:46
**CONDITIONAL PASS**  - DEACTIVATE Happy Path POST Test Case
Found existing bugs in this route, outside the scope of the work performed in this ticket. Opening a bug ticket and including it in a comment on this ticket prior to closing ticket.


- [ ] TC16 Use non-existant inbound_number_id `196522d9-a154-4ecf-b812-c30af75af194` in path parameter, expect  something not 500
**BUG**

ACTUAL RESPONSE:
```
500 
{
    "message": "Internal server error",
    "result": "error"
}
```

**Comment by cris-oddball** [comment] 2023-12-20 18:50
**CONDITIONAL PASS** - Update Negative POST test cases
Found existing bugs in this route, outside the scope of the work performed in this ticket. Opening a bug ticket and including it in a comment on this ticket prior to closing ticket.


- [ ] TC17 update the active to string using the ID 72a2198d-64a3-4fbf-8cc7-ea01928c32e3, expect 400 and a response indicating failure and reason
```
{
  "active": "foobar"
}
```

ACTUAL RESPONSE:
```
{
    "errors": [
        {
            "error": "ValidationError",
            "message": "active foobar is not of type boolean"
        }
    ],
    "status_code": 400
}
```

- [ ] TC18 update the auth_parameter to bool using the ID 72a2198d-64a3-4fbf-8cc7-ea01928c32e3, expect 400 and a response indicating failure and reason
```
{
  "auth_parameter": true
}
```

ACTUAL RESPONSE:
```
{
    "errors": [
        {
            "error": "ValidationError",
            "message": "auth_parameter True is not of type string"
        }
    ],
    "status_code": 400
}
```

- [ ] TC19 update the number to bool using the ID 72a2198d-64a3-4fbf-8cc7-ea01928c32e3, expect 400 and a response indicating failure and reason
```
{
  "number": true
}
```

ACTUAL RESPONSE:
```
{
    "errors": [
        {
            "error": "ValidationError",
            "message": "number True is not of type string"
        }
    ],
    "status_code": 400
}
```

- [ ] TC20 update the provider to bool using the ID 72a2198d-64a3-4fbf-8cc7-ea01928c32e3, expect 400 and a response indicating failure and reason
```
{
  "provider": true
}
```

ACTUAL RESPONSE:
```
{
    "errors": [
        {
            "error": "ValidationError",
            "message": "provider True is not of type string"
        }
    ],
    "status_code": 400
}
```

- [ ] TC21 update self_managed to string using the ID f72a2198d-64a3-4fbf-8cc7-ea01928c32e3, expect 400 and a response indicating failure and reason
```
{
  "self_managed": "foobar"
}
```

ACTUAL RESPONSE:
```
{
    "errors": [
        {
            "error": "ValidationError",
            "message": "self_managed foobar is not of type boolean"
        }
    ],
    "status_code": 400
}
```

- [ ] TC22 update url_endpoint to bool using the ID f72a2198d-64a3-4fbf-8cc7-ea01928c32e3, expect 400 and a response indicating failure and reason
```
{
  "url_endpoint": true
}
```

ACTUAL RESPONSE:
```
{
    "errors": [
        {
            "error": "ValidationError",
            "message": "url_endpoint True is not of type string"
        }
    ],
    "status_code": 400
}
```

- [ ] TC23 update number to non-unique +13035551212 using the ID f72a2198d-64a3-4fbf-8cc7-ea01928c32e3, expect 400 and a response indicating failure and reason
**BUG**
```
{
  "number": "+13035551212"
}
```

ACTUAL RESPONSE:
500
```
{
    "message": "Internal server error",
    "result": "error"
}
```

**Comment by cris-oddball** [comment] 2023-12-20 19:21
Two bug tickets created:
#1574
#1575

Closing ticket as completed!

**Closed by cris-oddball** 2023-12-20 19:21 UTC
Labels: Business Line Onboarding, Notify, QA, Dev Reviewed, PM Reviewed, QA Reviewed, Off-track
