### ISSUE TITLE
BUG: Unhandled Opt-Out

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1434] opened 2023-08-28 15:40 UTC
## Description
`record_status` is coming in as `OPTED_OUT` and we do not have that in our mapping, which leads to the notification not being properly updated. See the Additional Information section.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

## Steps to Reproduce

It is uncertain what steps can be used to replicate the issue, but we can prevent it.

## Impact/Urgency

This issue affects prod but appears to occur once every couple days, for now.

## Expected Behavior

- [x] `record_status` of `OPTED_OUT` is handled in `get_notification_status`
- [x] New or updated unit test for this behavior
- [x] Any non-success is logged 100% of the time

## Additional Info & Resources

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa3BEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cb0d26472dfa30d1645c097a2dc1caa492f21454/image.png)

`if` should check for `record_status` of `OPTOUT`:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcDVEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d2273291f7391fa48b7cc0a7a948435b2f2af342/image.png)

**Comment by cris-oddball** [comment] 2023-08-28 15:47
duplicate of #826 and #1319

**Comment by mjones-oddball** [comment] 2023-08-29 21:28
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1434?planning-poker) with Zenhub @babyjunior56 @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by k-macmillan** [comment] 2024-07-16 14:17
This issue has not been resolved:
![image](https://github.com/user-attachments/assets/459803b6-6e8e-4b2a-988d-e26b4e66de28)

**Closed** 2024-07-16 14:31 UTC
Labels: bug, Notify, Stretch, Dev Reviewed, PM Reviewed, QA Reviewed, superspeedy, PTEMS
