### ISSUE TITLE
Add Callback URL on email/sms POST Requests

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#2014] opened 2024-09-24 19:59 UTC
## User Story - Business Need
We want to ensure the new `callback_url` ends up in the database for that notification.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** VA Notify developer
**I want** `callback_url` to be available everywhere the Notification object is available
**So that** we can use it when appropriate

## Acceptance Criteria

- [x] TDD
~- [ ] Schema is updated with optional param for `callback_url`, using `https_url` in app/schema_validation/definitions.py~ See comments
- [x] `callback_url` is updated in the DB if one was present in the validated request
- [x] Deserializing the Notification object shows the callback URL
- [x] This work is added to the sprint review slide deck (key win bullet point and demo slide)

## QA Considerations

- Validate the POST route, including edge cases
- Validate the GET response returns the appropriate callback
- As needed after speaking with developer

**Comment by npmartin-oddball** [comment] 2024-09-25 13:07
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/2014?planning-poker) with Zenhub @coreycarvalho @cris-oddball @EvanParish @k-macmillan @kalbfled @MackHalliday @mchlwellman

**Comment by MackHalliday** [comment] 2024-10-02 18:15
NOTES 
- To test, send self notification email, check that `callback_url` appears in GET `{{notification-api-url}}/service/{{service-id}}/template/{{template-id}}`
- POST route - see `post_notification` method
- When you created, api key in DEV put name in Key. 
- Can use POSTMAN to test

**Comment by MackHalliday** [comment] 2024-10-02 23:00
Today 
- Picked up ticket and talked to Kyle 
- Started working on updates to POST /notifications (`post_notification` method). 

Tomorrow 
- Need to determine how this ticket fits in with completed ticket to '[Generate Signature Based on Params and API key](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/notification-api/2001)'
- Work on GET route

**Comment by MackHalliday** [comment] 2024-10-03 02:43
# Testing 
- GET {notification-api-url}}/v2/notifications/{{notification-id}}
- POST {{notification-api-url}}/v2/notifications/sms
   - phone_number 
   - recipient_identifier 
 - POST {{notification-api-url}}/v2/notifications/email
    - phone_number 
    - recipient_identifier 
- POST {{notification-api-url}}/v2/notifications/push (?) 
- POST {{notification-api-url}}/v2/notifications/push/broadcast (?) 


- Do we need to update `v3/notifications` routes ?

**Comment by MackHalliday** [comment] 2024-10-07 15:15
Note - check edge case for length of URL.

**Comment by MackHalliday** [comment] 2024-10-08 14:15
Discovered that updating the schema for the `https_url` to have a max length 255 has an unintended side affect of limiting the max length of the url on the ServiceCallback table. 

Should the url be constrained on the ServiceCallback table be constrained?

**Comment by kalbfled** [comment] 2024-10-08 14:45
@k-macmillan Mack and I discussed this.  The schema `https_url` is used to create and update rows in the ServiceCallback table.  It shouldn't be part of this ticket.

**Comment by cris-oddball** [comment] 2024-10-08 19:08
PR approved and merged, along with the QA PR that validates this work. 

Sending up to Perf, new regression will vet this, then can close ticket.

**Comment by cris-oddball** [comment] 2024-10-08 19:22
Passed valdiation

**Closed by cris-oddball** 2024-10-08 19:22 UTC
Labels: Notify, QA, Dev Reviewed, PM Reviewed, QA Reviewed, Off-track, zero-silent-failures
