### ISSUE TITLE
CD Pipeline to Staging

### ISSUE THREAD

**Issue by ldraney** [department-of-veterans-affairs/notification-api#1709] opened 2024-03-28 19:08 UTC
## User Story - Business Need

We want a fully automated CD pipeline to quickly get code changes into Production. This ticket picks up after the "deploy to perf & merge to release branch" and asks that a pipeline to "release to staging" is created.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)
**As a**  VANotify product manager and engineer
**I want**  to deploy the release branch to staging and run the regression after QA approval
**So that** the CI/CD pipeline is more fully automated.

### Additional Info and Resources
We have completed the work for the QA pipeline to merge to the Release branch upon QA approval.
The next step is to deploy the Release branch to staging once there is a merge to the Release branch.

Then add one more permission stop for QA
- The second permission stop is in preparation for deploy to prod, wherein QA approved that staging has passed all testing and monitoring. 

## Engineering Checklist

- [x] Determine appropriate branch protections for the release branch in association with the github actions user
- [x] Ensure the above changes to the release branch don't break the current Tag Push to Perf or Pre-Release to Staging workflows
- [x] Add permissions to deploy the release branch to staging and to confirm that SHA of release branch has passed staging tests.

## Acceptance Criteria
- Upon merge to the release branch there is a newly triggered workflow to deploy the Release branch to staging and run the Regression against staging.
- After the staging regression is run, there is a pause for an approval check from QA. Nothing happens after this (that is future work).
- Follow-on ticket to add versioning at the appropriate step within this flow (after regression passes in staging); VA expects versioning for APIs and so when we release to Prod, the branch needs to be tagged with a version.

## QA Considerations
- QA to test this workflow as needed and ensure it conforms to their expectations.

## Potential Dependencies
Setting up appropriate branch protections for the release branch and understanding their interaction with the github actions user

## Out of Scope
Actually deploying to prod is out of scope of this ticket. Prod requires a versioning solution prior full implementation.
~Monitoring needs to be greatly enhanced before this is feasible. ~ Coordination needs to be discussed.

**Comment by mjones-oddball** [comment] 2024-03-29 20:02
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1709?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @MackHalliday @mchlwellman

**Comment by ldraney** [comment] 2024-04-02 18:45
Kyle was able to make a status check branch protection that requires the Actions approval only available to QA, so the user issue I may have faced has been resolved!  Moving on.

**Comment by ldraney** [comment] 2024-04-02 19:00
workflow completed, but haven't tested yet.  
Probably need to test in my POC first but want to talk to Kyle, cause just by creating the new environments for approval I believe this is going to work just fine.

**Comment by ldraney** [comment] 2024-04-02 21:44
talked to Kyle, remembered and fixed a few things; and also realized a release branch may not be necessary, reducing the chance of bugs and also reducing complexity. 

sent a message to Kyle and Cris to sync on this. 

I'll sync with Cris tomorrow morning (once she has confirmed) and then hopefully be ready to sync with Kyle for parking lot.

**Comment by ldraney** [comment] 2024-04-03 15:02
Recent convo with Cris, and it seems assuming the latest release commit is fine moving forward. 

I'll adjust the workflow, add some tests to the PR with the POC, then open the PR.

**Comment by ldraney** [comment] 2024-04-03 21:14
Cannot yet test this code because of a situation in master. 
Will sync with QA tomorrow once that situation resolves.

**Comment by ldraney** [comment] 2024-04-04 18:12
finally got this merged!
asyncing with QA as this moves through the pipeline

**Comment by cris-oddball** [comment] 2024-04-04 19:24
**QA PASSES**

Worked with Lucas after this workflow was merged.

Noted that the lines connecting the staging steps in the UI don't exactly match up with the perf lines, but the code functions as expected and so leaving that alone for now.

<img width="1261" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjQzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6158bfc05f0562cf258c9cca55bbf17ca9bc5d2f/Screenshot%202024-04-04%20at%2012.54.04%E2%80%AFPM.jpg" alt="Screenshot 2024-04-04 at 12.54.04 PM.jpg" />

<img width="1298" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjgzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--37dd61341981eadfb077d60a8ec612feff484374/Screenshot%202024-04-04%20at%2012.53.53%E2%80%AFPM.jpg" alt="Screenshot 2024-04-04 at 12.53.53 PM.jpg" />


Also had a minor branch protection issue that was resolved and then I received the final pause.

All steps work as expected. 
The release branch was confirmed as the branch sent to staging.
The QA regression was confirmed as having regressed the correct commit.

Closing ticket.

**Comment by cris-oddball** [comment] 2024-04-05 17:51
Re-opening ticket because we still need the follow-on ticket for finishing this pipeline out to Prod. 
@ldraney ^^^

**Comment by cris-oddball** [comment] 2024-04-05 17:55
Two tix forthcoming: 1) versioning and 2) deploy to prod.

**Comment by ldraney** [comment] 2024-04-07 04:18
1. Here is [the versioning ticket](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/vanotify-team/1288)

**Comment by ldraney** [comment] 2024-04-07 04:55
2. Here is the [deploy to prod ticket](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/vanotify-team/1290)
3. Here is another [ticket to publish the release notes ](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/notification-api/1721)(once deploy to prod is setup in the pipeline).

**Closed** 2024-04-07 04:57 UTC
Labels: Notify, QA, devops, Dev Reviewed, PM Reviewed, QA Reviewed
