### ISSUE TITLE
V3 - Add Default SMS Sender Logic

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#1504] opened 2023-10-20 19:02 UTC
We want to ensure V3 has feature parity with V2. Clients can send an SMS request with or without an sms_sender_id. If they send without, then we must look up the default sender assigned to the service and send the SMS from that sender.

## User Story - Business Need

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** VA Notify Client
**I want** to send SMS notification to Veterans
**So that** I can deliver timely, actionable information

### Additional Info and Resources

- There was already work completed to deliver sms notifications with a specified sms_sender_id - #1361

## Engineering Checklist

Changes should be made [here](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/celery/v3/notification_tasks.py#L109).  The existing v2 logic is [here](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/v2/notifications/post_notifications.py#L77).

- [x] Reach out to @kalbfled for a little intro sync since he's the SME on this project
- [x] Add logic to check for a default sms sender on the service if sms_sender_id is not provided (basically a copy-and-paste)
- [x] Persist the sms_sender_id associated with the default sender in the database
- [x] Write new unit tests [here](https://github.com/department-of-veterans-affairs/notification-api/blob/master/tests/app/celery/v3/test_notification_tasks.py)

### Givens

- A default SMS sender is assigned to the service
- There is another SMS sender assigned to the service which is not the default

### Cases

- [x] Send an sms without specifying a sender

1. Send an sms request through postman to `/v3/notifications/sms` and do not include `sms_sender_id` in the request body
2. You should receive the sms from the default number assigned to the service

- [x] Send an sms with a sender that is the default

1. Send an sms request through postman to `/v3/notifications/sms` and include a valid `sms_sender_id` which is the default in the request body
2. You should receive the sms from the sender associated with the id provided

- [x] Send an sms with a sender that is not the default

1. Send an sms request through postman to `/v3/notifications/sms` and include a valid `sms_sender_id` which is not the default in the request body
2. You should receive the sms from the sender associated with the id provided

 ### Givens
There is not a default sms sender assigned to the service

### Cases
- [x] Missing default sender

1. Send an sms request through postman to `/v3/notifications/sms` and do not include `sms_sender_id` in the request body
2. Then upon using GET notification you should see a validation error stating no default sender was found

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._
- [ ] Validate above cases in Perf once deployed there
- [x] Automate or create ticket to automate

## Out of Scope
There is a separate ticket to restore multiple provider logic #1505

**Comment by cris-oddball** [comment] 2023-11-08 14:13
Question here @mjones-oddball @kalbfled @nikolai-efimov 

I was playing around with this on DEV since Nikolai had deployed it there and checked all the boxes for the AC and discovered....

In the GET v2/notifications/:notification_id route for a an sms sent through the v2 POST route, I see the following in the response: `"sms_sender_id": "17060187-ad48-4391-a465-aacd048b4ae0",`

However, in the GET v2/notifications/:notification_id route for a an sms sent through the v3 POST route, that property is set to null; `"sms_sender_id": null,`

Is this desired? The ticket actually doesn't mention what to do with that field. I would think we still want to return that value? It matters for automation, since I would want to verify that when sent using X, then X actually sent the message.

**Comment by nikolai-efimov** [comment] 2023-11-08 15:43
@cris-oddball , let's discuss that in the stand-up meeting.

**Comment by nikolai-efimov** [comment] 2023-11-09 03:35
Code and tests are updated and ready to be tested. https://github.com/department-of-veterans-affairs/notification-api/pull/1532

**Comment by cris-oddball** [comment] 2023-11-09 20:24
Code approved, merged and deployed to Perf, testing in progress.
Created [new ticket](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/notification-api-qa/161) to automate this feature.

**Comment by cris-oddball** [comment] 2023-11-09 20:47
PASSES QA Testing in Perf

- **TC01 PASSED** Send an sms without specifying a sender (should use default sms sender id beginning with `17adae4d`), expect 202 on POST v3 sms and 200 on GET v2 notifications/:notification_id that includes the service's default sms_sender and a status of delivered.

payload
```
{
    "template_id": "{{sms-template-id}}",
    "phone_number": "<redacted>"
}
```
202 response:
```
{
    "id": "20dce0b5-0b60-4e38-a80d-add4970ed71e"
}
```

GET response properties that validate this works as intended:
```
    "sms_sender_id": "fccd9e82-<snip>",
    "status": "    "status": "delivered",
```
<br>

- **TC02 PASSED** Send an sms by specifying the default sms sender (beginning with `17adae4d`), expect 202 on POST v3 sms and 200 on GET v2 notifications/:notification_id that includes the sms_sender and a status of delivered.

payload
```
{
    "template_id": "{{sms-template-id}}",
    "phone_number": "<redacted>",
    "sms_sender_id": "{{sms-sender-id}}"
}
```
202 response
```
{
    "id": "fbb331bc-501d-4b18-89d8-a588fc112b19"
}
```

GET response properties that validate this works as intended:
```
    "sms_sender_id": "fccd9e82-<snip>",
    "status": "delivered",
```
<br>

- **TC03** Send an sms by specifying an alternate sms sender (beginning with `b6288085`), expect 202 on POST v3 sms and 200 on GET v2 notifications/:notification_id that includes the sms_sender and a status of delivered.

payload
```
{
    "template_id": "{{sms-template-id}}9",
    "phone_number": "<redacted>",
    "sms_sender_id": "b6288085-<snip>"
}
```
202 response
```
{
    "id": "217a5be1-3d8d-45e6-975a-468419985915"
}
```

GET response properties that validate this works as intended:
```
    "sms_sender_id": "b6288085-<snip>",
    "status": "delivered",
```
<br>


- **TC04** Send an sms from a service that does not have a default sms sender assigned, expect 202 on POST v3 sms and 200 on GET v2 notifications/:notification_id that includes a status of technical-failure and the reason for that failure.
Created service in Perf via Portal (so, no default sender is set) and added an sms template
Service is 
payload


202 response

GET response properties that validate this works as intended:

**Comment by cris-oddball** [comment] 2023-11-09 21:00
[Regression Results in Perf](https://github.com/department-of-veterans-affairs/notification-api-qa/actions/runs/6817316114) PASSED  
`172 passed, 4 xfailed in 257.79s (0:04:17)`

**Closed by cris-oddball** 2023-11-09 21:00 UTC
Labels: Notify, QA, Dev Reviewed, PM Reviewed, QA Reviewed
