### ISSUE TITLE
Spike: Process Delivery Status appears to enter  a final state and then exit it

### ISSUE THREAD

**Issue by justaskdavidb2** [department-of-veterans-affairs/notification-api#1294] opened 2023-05-23 22:41 UTC
## Business Goal

**Problem:**
In one instance, we received a delivered status, then a sent status, and finally a sending status (just happened to be out of order). Our system should have received the delivered status and ignored any other status relayed to us. It should not have updated the database to "sending" after receiving the status of "delivered". 

**There are four goals for the spike**
- Implement a quick fix until a permanent solution can be deployed.
- Determine level of effort required to achieve the "permanent solution"
- Create any additional stories to achieve the "permanent solution"
- Discuss / Identify tech debt concerns and create stories for each

## Observation
We have observed the following very rare conditions:

- process delivery statuses can be  received out of order
- cloudwatch logs can show a notification as having a status of delivered but the database shows a status of sending/sent

**We would like the following:**

- We would like to enforce order of the status for a notification such that sending->sent->delivered is strict. A notification can only go from sending->sent and sent->delivered. The following is not possible sent->sending->delivered.

- We would like to make sure that race condition/concurrency of processes does not prevent the database from having the correct value of "delivered"

- We would like cloudwatch logs for all given notifications should match what we see in the database
- Test cases to check for possibility of race condition

- [x]  Discuss with QA

## Steps to Reproduce

1. In QA sent a sms message using Twilio.
2. Observe the logs in cloudwatch showing each delivery status of a given message.
3. Note any delivery_status that entered a "final state" but was later updated to a different status. 

## Workaround
None

## Impact/Urgency
Deliver status Twilio message is not accurately reporting the delivery status. This is data integrity issue.

MJ notes: This will skew our reporting in Domo, which clients use. It will look like the deliverable percentage is lower than it should be as a result.

## Expected Behavior
Our system should have received the delivered status and ignored any other status relayed to us. It should not have updated the database to "sending" after receiving the status of "delivered". 

- [x] Discover root cause for why the delivery status is not staying "delivered"
- [x] Create test case to detect the occurrence of this particular race condition in the future
- [x] The  delivery status a notification cannot escape "delivered" once it is entered. .

## QA Considerations
 - [ ] delivery status messages do not go from 'delivered' to 'sending' in the logs - check the regression, it may be hung at a specific state if it missed the initial 'delivered' status and then a different status was sent - the last test will usually fail.
 - [ ] regression passes

## Additional Info & Resources
![image__12_](https://github.com/department-of-veterans-affairs/notification-api/assets/111803622/f30a9ede-72e3-4f2a-8019-075e79e66cee)

**Comment by k-macmillan** [comment] 2023-05-25 17:14
Due to the asynchronous nature this may have been a stale read. There are various methods to prevent stale reads. Some [may not work for us](https://docs.sqlalchemy.org/en/20/orm/queryguide/query.html#sqlalchemy.orm.Query.with_for_update).

**Comment by tabinda-syed** [comment] 2023-06-02 19:39
Re-pointed to 5 based on team's discussion at 6/1 standup and in the team Slack channel on 6/2.

**Comment by cris-oddball** [comment] 2023-06-08 17:12
In order to test this code, the code was deployed to Perf and the ALB rules changed such that Twilio delivery status updates go to nowhere so that the delivery status lambda can have some test cases pushed through it.

TEST SET ONE - delivered-sent-sending
- send a message through Postman to Twilio, get the notification_id and check the notification object for the "provider_reference"
- create a UTF-8 string that is the body for each of the delivery statuses and update the MessageSid to the provider_reference
- Base64 encode each body and send that through the project-perf-delivery-status-processor-lambda test tab using an existing test case but changing the body to the base64 body
- NOTE that for this test, the ALB had been reverted back on an Infra deploy, so Twilio had already reported it as delivered. This test is still valid, because the first status I would have set it to would have been delivered.

TEST RESULTS from select perf api logs
```
[2023-06-08 16:47:04,636: INFO/ForkPoolWorker-4] SQS callback received the same status of delivered for notification 68a6ecef-4a45-4423-9f39-f8495d09d04f)
[2023-06-08 16:47:47,815: WARNING/ForkPoolWorker-4] Invalid callback received. Notification id 68a6ecef-4a45-4423-9f39-f8495d09d04f received a status update to sent 0:05:16.389361 after being set to delivered. sms sent by twilio
[2023-06-08 16:48:28,256: WARNING/ForkPoolWorker-4] Invalid callback received. Notification id 68a6ecef-4a45-4423-9f39-f8495d09d04f received a status update to sending 0:05:56.830918 after being set to delivered. sms sent by twilio
```

The GET route in Postman continued to report back in the response that the message was delivered.

**Comment by cris-oddball** [comment] 2023-06-08 17:28
Changed the ALB rule

TEST SET TWO: sent, delivered, sending
TEST RESULTS for select perf logs
```
[2023-06-08 17:18:41,492: INFO/ForkPoolWorker-4] Successfully sent sms for notification id: 677e357b-b396-43ad-8697-8d8eba9d0348
[2023-06-08 17:23:34,804: INFO/ForkPoolWorker-4] Delivery Status callback return status of sent for notification:  677e357b-b396-43ad-8697-8d8eba9d0348
[2023-06-08 17:24:08,687: INFO/ForkPoolWorker-4] Delivery Status callback return status of delivered for notification:  677e357b-b396-43ad-8697-8d8eba9d0348
[2023-06-08 17:24:40,360: WARNING/ForkPoolWorker-4] Invalid callback received. Notification id 677e357b-b396-43ad-8697-8d8eba9d0348 received a status update to sending 0:00:31.667464 after being set to delivered. sms sent by twilio
[2023-06-08 17:24:40,361: INFO/ForkPoolWorker-4] Delivery Status callback return status of sending for notification:  677e357b-b396-43ad-8697-8d8eba9d0348
```

The GET route in Postman continued to report back in the response that the message was delivered.

**Comment by cris-oddball** [comment] 2023-06-08 17:36
TEST SET THREE:  sending, delivered, sent
TEST RESULTS for select perf logs
```
[2023-06-08 17:29:52,087: INFO/ForkPoolWorker-4] Successfully sent sms for notification id: 9ab27462-f081-4ec2-be75-9db647217031
[2023-06-08 17:32:06,522: INFO/ForkPoolWorker-4] SQS callback received the same status of sending for notification 9ab27462-f081-4ec2-be75-9db647217031)
[2023-06-08 17:32:06,522: INFO/ForkPoolWorker-4] Delivery Status callback return status of sending for notification:  9ab27462-f081-4ec2-be75-9db647217031
[2023-06-08 17:32:32,770: INFO/ForkPoolWorker-4] Delivery Status callback return status of delivered for notification:  9ab27462-f081-4ec2-be75-9db647217031
```

The GET route in Postman continued to report back in the response that the message was delivered.

**Comment by cris-oddball** [comment] 2023-06-08 18:35
Merged to master. This code has just been tested on Perf (above), so running the regression.

**Comment by cris-oddball** [comment] 2023-06-08 18:56
`92 passed, 1 xfailed in 106.58s (0:01:46)`

QA PASSES this ticket. Closing.

**Closed by cris-oddball** 2023-06-08 18:56 UTC
Labels: Notify, QA, Dev Reviewed, PM Reviewed, QA Reviewed, Off-track
