### ISSUE TITLE
BUG: Email Delivered Status with Failure Status Reason

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#1630] opened 2024-02-05 20:14 UTC
## Description
Beverly was pulling stats in BigQuery and Domo and noticed that some delivered notifications are showing failure status reasons.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

## Steps to Reproduce

1. Go to [Prod Statistics in BigQuery](https://console.cloud.google.com/bigquery?project=vsp-analytics-and-insights&pli=1&ws=!1m5!1m4!4m3!1svsp-analytics-and-insights!2splatform_vanotify!3sprod-statistics)
2. Find all instances of notifications where the status is delivered and the status reason isn't blank
```
SELECT
  date,
  service_name,
  template_name,
  status,
  status_reason
FROM
  `vsp-analytics-and-insights.platform_vanotify.prod-statistics`
WHERE
  status = "delivered"
  AND status_reason IS NOT null
```
3. See Results

Example results below
<img width="1097" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXd0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e6778daec67ee9cb6b7e2ab291d27819da594d0/image.png" alt="image.png" />

You can tell that this is only happening with hard and soft bounces by returning a distinct status_reason list.
```
SELECT
  DISTINCT status_reason
FROM
  `vsp-analytics-and-insights.platform_vanotify.prod-statistics`
WHERE
  status = "delivered"
  AND status_reason IS NOT null
```
Results:
- Temporarily failed to deliver email due to soft bounce
- Failed to deliver email due to hard bounce

## Impact/Urgency

High - We cannot know If notifications are inaccurately being set to delivered until we investigate the root cause of the status/status reason combination.

## Expected Behavior

**3 pt limit, please keep the team informed if this becomes more complex than expected so we can re-evaluate next steps/additional tickets**

- [ ] Notifications in a delivered state should not have a status_reason. Only notifications which are successfully delivered, as reported by the provider, should be updated to a status of delivered.

### Checklist
- [ ] Dive into our database (to get notification ids) and DD logs to trace down what caused this mixture of status and reason. We need to understand what statuses we received from the provider in these cases and how we processed them.
    - [ ] Once the cause is known, discuss with the team to ensure we still think it's feasible to do data cleanup within this ticket
- [ ] Clean up notifications/notification history in the database to reflect accurate status and status reason combination
- [ ] Clean up BigQuery Prod stats table to reflect accurate status and status reason combination

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

We don't yet know how this was caused to know how to replicate it.

## Additional Info & Resources

- [AWS docs](https://docs.aws.amazon.com/ses/latest/dg/send-email-concepts-deliverability.html)

**Comment by mjones-oddball** [comment] 2024-02-05 20:58
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1630?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @mchlwellman

**Comment by mjones-oddball** [comment] 2024-02-06 17:08
@bevnobev @cris-oddball Update on this bug:
@k-macmillan and I discussed. SES does async processing. Soft bounces are retried by SES automatically. We trust the delivered status and should ensure it's honored in this case. In the hard bounce case only DNS lookup failures are retried by SES so we are a little unclear if we can/should trust delivered and will escalate a production impact ticket to Amazon for them to confirm before we decide. It's likely the same case as soft bounce due to async processing, but just want to be 100% as hard bounces are usually permanent failures. See more info here: https://docs.aws.amazon.com/ses/latest/dg/send-email-concepts-deliverability.html
and
> Bounces can also be synchronous or asynchronous. A synchronous bounce occurs while the email servers of the sender and receiver are actively communicating. An asynchronous bounce occurs when a receiver initially accepts an email message for delivery and then subsequently fails to deliver it to the recipient.

**Comment by k-macmillan** [comment] 2024-02-06 23:41
Identified where in the code this happening. We get a status of `delivered`, then we get a `bounce` status update from AWS. We usually consider `delivered` to be the final resting point of a message, but that is not always the case. Will discuss with @mjones-oddball tomorrow.

<img width="732" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGsxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e1787a218a39af3af5908cc30decffae6d3760f/image.png" alt="image.png" />

**Comment by k-macmillan** [comment] 2024-02-08 15:51
Hard bounces are confirmed failures and should have their status changed to `permanent-failure`. I have asked for clarification on soft bounces so we can determine a path forward for those.

**Comment by k-macmillan** [comment] 2024-02-08 21:27
Soft bounces may also be considered an end-state for that notification attempt. Handled both hard/soft bounces and prevented updating the status back to delivered if there is a bounced status, per AWS discussion.

**Comment by cris-oddball** [comment] 2024-02-09 15:28
PR approved and merged. Due to the complexity of integration testing, replying on unit tests for this one. Sent to Perf, where a regression will be run.

**Comment by cris-oddball** [comment] 2024-02-09 15:41
Regression passed.
@k-macmillan @mjones-oddball are we doing any data clean-up on a second ticket or on this ticket? 
If a second ticket I will hold this here in QA until I get the new ticket linked here.

**Comment by cris-oddball** [comment] 2024-02-09 18:02
No need to hold this ticket for the clean-up. Closing as done.

**Closed by cris-oddball** 2024-02-09 18:02 UTC
Labels: Notify, QA, Dev Reviewed, PM Reviewed, QA Reviewed
