### ISSUE TITLE
Move to pytest 5

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#297] opened 2020-12-21 16:47 UTC
# Value Statement
**As** VANotify Developer
**I want to** use the latest version of pytest library
**So that** I know I am using the most up to date testing framework and there are no dependency conflicts

# Acceptance Criteria
**GIVEN** I run a pytest
**THEN** I am using the latest version of the pytest library

# Checklist
- [ ] Upgrade pytest requirements file
- [ ] Fix all pytest fixtures

# Assumptions
-

# Additional Info/Resources
-

# Out of Scope
-

# Open Questions
-

**Comment by philherbert** [comment] 2020-12-31 15:49
Closing as duplicate of #299 (which I know is newer, but has more detail)

**Closed by philherbert** 2020-12-31 15:49 UTC
Labels: Tech Debt
