### ISSUE TITLE
QA Suite - API Deployment

### ISSUE THREAD

**Issue by ldraney** [department-of-veterans-affairs/notification-api#1326] opened 2023-06-19 20:17 UTC
## User Story - Business Need
The business need for this ticket is to enhance deployment stability and quality assurance by automatically triggering a comprehensive test suite (`notification-api-qa` repo `regression.yml`) whenever there is a deployment to the `perf` or `staging` environments in the `notification-api` repo. This ensures that any issues are immediately caught and rectified, maintaining the integrity and reliability of the deployed software.

- [x] ticket is understood and discussed with QA

### User Story(ies)
**As a** developer  
**I want** the notification-api repo workflow `deployment.yml` to automatically trigger the `notification-api-qa` repo `regression.yml` suite whenever there is a deployment to `perf` or `staging` environments  
**So that** every deployment is thoroughly tested, and any issues are caught and reported immediately. 

## Additional Info and Resources
This requirement excludes pre-release and DOES NOT include when tag creation triggers a deployment to perf. However, no additional configuration is likely necessary in this situation since the `tag_trigger.yml` already states: 
``` 
  run-deployment:
    needs: [setup-env, run-build]
    uses: ./.github/workflows/deployment.yml
    with:
      environment: "perf"
      ref: "${{ needs.setup-env.outputs.git-tag }}"
    secrets: inherit
```
Still, it should include a branch option for input, but default to master. The trigger is `notification-api` will instruct the QA suite to run its action.

## Engineering Checklist
- [x] Confirm that all QA suite actions are running smoothly before setting up repo-to-repo action communication
- [x] Determine the best way for setting up repo-to-repo action communication.  
     ~- [ ] (Personally I prefer dispatch with a Github Token in the notification-api repo should work, setting up the GITHUB_TOKEN to a specific value in a step)~
     ~- [ ] [Github Deploy Keys](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/managing-deploy-keys#deploy-keys) are another option~
- [ ] Configure `notification-api` to trigger `notification-api-qa` `regression.yml` suite on deployment to `perf` or `staging`
~- [ ] Make deploy to `perf` and `staging` mandatory on master branch~
- [ ] QA has confirmed the above configuration meets team needs

## Acceptance Criteria
- When the deployment is pushed to `perf` or `staging`, the `notification-api-qa` regression suite should automatically be triggered and be able to run successfully.

## QA Considerations
QA will need to verify that the QA suite runs successfully whenever there is a deployment to `perf` or `staging`.

## Potential Dependencies
- This depends on all QA suite actions running smoothly before attempting to call these actions from the `notification-api` repo.

## Out of Scope
- The deployment to `dev` environment should not be impacted by these changes and does not have to be on the master branch.
- Any changes in the Workflow process upon test failure.
- Do **no** work to trigger the regression on a tag push to perf or on a pre-release.

**Comment by mjones-oddball** [comment] 2023-06-21 14:08
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1326?planning-poker) with Zenhub @cris-oddball @EvanParish @justaskdavidb2 @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by cris-oddball** [comment] 2023-09-07 17:40
Discussed a few things with Lucas.
- deploy keys may not work, it will be ugly, it's not designed for this
- setting access to the repo as described [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#allowing-access-to-components-in-a-private-repository) and [here](https://docs.github.com/en/actions/creating-actions/sharing-actions-and-workflows-with-your-organization) is not possible, since the QA repo is internal and the API repo is public

Lucas will investigate cloning the QA repo into a GitHub runner and running the tests against the public endpoints (private are covered in the nighly regressions) with `--platform local`.  If the output ends up being truncated, will look into the self-hosted runner (the QA ec2) and back to testing the private endpoints)

**Comment by cris-oddball** [comment] 2023-09-07 20:56
Added public key to deploy keys and private key to repository secrets in notification-api repo .
Lucas to figure it out from here.

**Comment by ldraney** [comment] 2023-09-08 02:15
deploy keys are not intended to be used how we need.  Rather, it should be  with the intended path for [sharing actions and worfklows within an organization](https://docs.github.com/en/actions/creating-actions/sharing-actions-and-workflows-with-your-organization), but we don't have that option because our public notification-api repo can't use the workflow in the notification-api-qa.  [another relevant doc ](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#allowing-access-to-components-in-a-private-repository)

Cris suggested a better naming convention, and then essentially copying regression.yml to the notificaiton-api repo and just pull down the latest version of master.  I think that's the cleanest option we have at this point.  Ticket is still in a three I'd say if I can create a solution by EOD Friday.

**Comment by ldraney** [comment] 2023-09-08 04:31
new tagging strategy works
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWQ5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--373d492bbdce604fbe05b322b93dd04f2d8fd6af/image.png)

**Comment by ldraney** [comment] 2023-09-08 04:36
Within the `qa` repository, on the `1326qa` branch, we've implemented an update to our CI/CD pipeline. Now, whenever a commit is made to the `master` branch, our build system will automatically generate a Docker image and tag it as `master`. This approach ensures that any Docker image with the `master` tag will always represent the most recent commit from the `master` branch. As a result, we can guarantee that the `master` tag consistently points to the latest stable version of our software.

**Comment by ldraney** [comment] 2023-09-08 04:37
next step should simply be to pull and run the image in the new workflow I'm writing for notification-api.  
It will only run against the public endpoints, which is sufficient since we now have a nightly regression test of the private endpoints.

**Comment by ldraney** [comment] 2023-09-08 05:08
I need to determine our strategy for getting the .env file onto the runner. 
This command is not secure running :
```
          aws ssm get-parameter --name /notification-api-qa/env --with-decryption | jq '.Parameter.Value' -r > .env
```
I propose

**Comment by ldraney** [comment] 2023-09-08 21:05
wantd to add one more picture of how the tagging is working so we can feel good about it:  If you have questions then please message me for a hangout!
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaHFDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4c93f459b9285433d5ce16f1630783df5e2159b6/image.png)

**Comment by tabinda-syed** [comment] 2023-09-11 15:05
Increased points to 5. @ldraney to add more complexity details.

**Comment by ldraney** [comment] 2023-09-11 16:29
Summary of increased complexity:
1. The deploy-keys are not meant for our use case
2. Docker tagging is a better option, but the two complexities are 1: the tagging itself and 2: running the suit via the action runner. 

The tagging is working as expected. 
The runner is almost there, seems that it will run with a few tweaks to the script. 
Then test the whole thing together.

**Comment by cris-oddball** [comment] 2023-09-12 21:59
Both API and QA PRs were merged to master, but the QA repo is failing on the [Build & Push](https://github.com/department-of-veterans-affairs/notification-api-qa/actions/runs/6165251692) action on that merge.

API master has been tagged for this code change but not pushed to Perf yet because of the above build failure.

**Comment by cris-oddball** [comment] 2023-09-13 13:07
Moving back to DEV lane. 
@ldraney please walk me through your new hotfix as soon as possible. The nightly failed last night because of the build issue.

Also, please check off your checklist in the description.

**Comment by cris-oddball** [comment] 2023-09-13 19:23
Significant refactor of both the work in notification-api and notification-api-qa repos.
Code approved and merged.
Tagged and deployed to Perf.

This was tested by running the workflow from the branch against master and in perf against the public endpoints.

Something to note is that because we made the decision to run the regression container in the GitHub runner VM that the first set of tests failed due to a timeout to our public API endpoints from the GitHub network. This may become an issue for us and needs to be revisited when I return from vacation on the 28th.

If instead we used the self-hosted runner to load the container onto the EC2 then the regression would run against the private endpoints and be less likely to timeout due to whatever network latency exists between GitHub and our ALB.

Lucas will discuss this with Kyle when he gets back/while I'm away.

Closing ticket.

**Closed** 2023-09-13 19:23 UTC
Labels: Notify, QA, devops, Dev Reviewed, PM Reviewed, QA Reviewed, Off-track
