### ISSUE TITLE
Part 2 of Provider Logic Issue - Email

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#975] opened 2022-11-29 22:35 UTC
Please see the prior ticket for details of what was done for SMS. https://github.com/department-of-veterans-affairs/notification-api/issues/944

- [x] Deactivate GovDelivery Provider in all envs as Beverly has confirmed this should no longer be used
    - [x] If any templates are using GovDelivery, please remove the provider id
    - [x] User flow updates
- [x] Update all services containing the permission "email" to use the email_provider_id for AWS SES in:
    - [x] Dev
    - [x] Staging
    - [x] Perf  (available through the staging instance or dev-bastion-host)
    - [x] Prod
- [x] Email provider logic should still be retained, but should use the provider id defined in the template first, service second, and logic based on priority order third.
    - [x] User flow update
- [ ] QA checkpoint - what tests are needed?
    - [x] Help with user flow recommendations
    - [ ] Validate what's in the database to ensure all envs were populated as expected

Reference Info
Info about the update statement used in the previous task [here](https://github.com/department-of-veterans-affairs/notification-api/issues/944#issuecomment-1325630689). I believe postgresql handles joins in updates a little differently than other sqls. See https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-update-join/

Could be something like... 
``` sql

UPDATE services s
SET s.sms_provider_id = "<AWS SES ID for env>"
FROM service_permissions sp
WHERE s.id = sp.service_id
AND sp.permission = "email"
AND s.email_provider_id IS NULL;
```

**Comment by mjones-oddball** [comment] 2022-11-29 23:12
@cris-oddball Since you weren't included in QA on the last one I want to make sure you're aware of part 2 for email!

**Comment by mjones-oddball** [comment] 2022-11-29 23:13
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/975?planning-poker) with Zenhub @cris-oddball @EvanParish @ianperera @jakehova @k-macmillan @kalbfled @ldraney @trevor2718

**Comment by mjones-oddball** [comment] 2022-11-30 17:54
@cris-oddball or @kalbfled Please add thoughts on userflows when you get a chance (since you had knowledge/experience from t he last ticket)

**Comment by kalbfled** [comment] 2022-12-02 06:33
I completed all of the prescribed database updates.

**Comment by kalbfled** [comment] 2022-12-02 19:20
I don't think any changes are necessary for the e-mail provider logic.  It works that way now.  My changes for #944 didn't alter that.

**Comment by kalbfled** [comment] 2022-12-02 20:47
I will merge this when I have QA clearance.

**Comment by cris-oddball** [comment] 2022-12-06 19:54
@kalbfled in order for me to test this, the code has to be merged. If that closes this ticket, I will re-open it.

**Comment by kalbfled** [comment] 2022-12-06 20:19
I merged the associated PR with it's one-line change, but I'm keeping this ticket open while I investigate Cris's concerns.

**Comment by kalbfled** [comment] 2022-12-06 22:42
The problem is that my query for determining which services have permission to send e-mail uses the wrong table.  I should select from `service_permissions` rather than `permissions`.  I will update the queries I recorded in a comment above on 12/2, and I will execute the queries in all environments.

**Comment by kalbfled** [comment] 2022-12-07 00:04
I updated all environments using these queries:
```sql
-- Update services with e-mail permission to use AWS SES.
with q as (select distinct(service_id) from service_permissions where permission='email')
update services set email_provider_id='<ses provider id>' where id in (select * from q);

-- Find previous mistakes.
with q as (select distinct(service_id) from service_permissions where permission='email')
select name, id, email_provider_id from services where email_provider_id is not null and id not in (select * from q);

-- Correct previous mistakes by setting email_provider_id to NULL for service that don't have "email" permission.
with q as (select distinct(service_id) from service_permissions where permission='email')
update services set email_provider_id=NULL where email_provider_id is not null and id not in (select * from q);
```

**Comment by cris-oddball** [comment] 2022-12-07 17:20
@kalbfled Yes, that looks correct for Dev in terms of `email_provider_id ` set on the services that have the email perms. Go ahead and update the other envs, please!

**Comment by cris-oddball** [comment] 2022-12-07 18:03
Now that user flows has been updated with the correct provider 'ses', there's no need to add or update anything there. That will be handled in the new regression, so I ticked off those boxes.

**Comment by cris-oddball** [comment] 2022-12-08 17:03
Tested on dev, perf and staging

- All services containing the permission "email" use the email_provider_id for AWS SES
- No templates in any service are using govdelivery

**Closed** 2022-12-08 17:03 UTC
Labels: Notify
