### ISSUE TITLE
Update check_and_queue_callback Logic for a callback url

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#2012] opened 2024-09-24 19:28 UTC
## User Story - Business Need
As part of the work to enhance client experience and reduce opportunities for silent failures, we are enabling a `callback_url` as part of the notification request. If there is a `callback_url` in the Notification object it will supersede any service-level callback.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** Service using VA Notify
**I want** to be able to specify callbacks at the request-level
**So that** we have more agency

### Additional Info and Resources

The `check_and_queue_callback_task` method was only built with service callbacks in mind.

## Acceptance Criteria

- [x] TDD
- [x] Existing service-level callback logic moved to a new method, untouched
- [x] New `callback_url` based logic is in a separate method
- [x] Logic in `check_and_queue_callback_task` calls one method or the other
- [x] New method collects data using the `create_delivery_status_callback_data_v3` method
- [x] Signature is retrieved with `generate_callback_signature` method
- [x] 400, 401, and 403 responses need to be logged as error so we can surface those with our clients.
- [x] Update [callback docs](https://github.com/department-of-veterans-affairs/notification-api/blob/main/app/callback/README.md) for request level callbacks
  - [x] make note that we currently do not offer SQS callback
- [x] This work is added to the sprint review slide deck (key win bullet point and demo slide)

## QA Considerations

Edge cases such as invalid URLs or clients rejecting the request due to validation.

**Comment by kbelikova-oddball** [comment] 2024-09-24 21:29
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/2012?planning-poker) with Zenhub @coreycarvalho @cris-oddball @EvanParish @k-macmillan @kalbfled @MackHalliday @mchlwellman

**Comment by EvanParish** [comment] 2024-10-09 15:03
I've started writing tests for this and since the blocking ticket is now merged, I am starting implementation work.

**Comment by EvanParish** [comment] 2024-10-09 22:13
I made some good progress today, but I have a few questions I'll have to run by Kyle / team tomorrow before I can finish this work.

**Comment by EvanParish** [comment] 2024-10-11 17:42
I did some testing yesterday and it's looking promising so far! There were a couple things I wanted to look into today before opening the PR for review, so I'm just wrapping that up.

**Comment by cris-oddball** [comment] 2024-10-14 17:06
**QA TESTING IN PROGRESS**

- [ ] Regression in Perf passes
- [ ] Service callbacks still function as before if a notification is sent without a callback.
- [ ] Notification callback w/o service callback results in a logged message, 'Callback successfully sent for notification' and includes the header 'x-enp-signature'
- [ ] Notification callback w/ service callback results in a logged message, 'Callback successfully sent for notification', only the notification callback is issued, not the service callback, and includes the header 'x-enp-signature'
- [ ] Notification callback that returns 4xx that is not a 429 is not retryable w/ log 'Non-retryable error sending callback for notification' and 'will not retry' (note there are a lot of 4xx errors, pick 3)
- [ ] Notification callback that returns 429 is retryable w/ log 'Retryable error sending callback for notification'
- [ ] Notification callback that returns 5xx is retryable w/ log 'Retryable error sending callback for notification'

**Closed** 2024-10-14 17:57 UTC
Labels: Notify, QA, Dev Reviewed, PM Reviewed, QA Reviewed, zero-silent-failures
